<?php
/**
 * EventosHttpsSefinNfseGovBrSefinnacionalApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * EventosHttpsSefinNfseGovBrSefinnacionalApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventosHttpsSefinNfseGovBrSefinnacionalApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'eventosGet' => [
            'application/json',
        ],
        'eventosPost' => [
            'application/json',
        ],
        'nfseChaveAcessoEventosGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation eventosGet
     *
     * Retorna NFS-e e seus eventos relacionados a partir da consulta pela chave de acesso da NFS-e.
     *
     * @param  string $chave_acesso Chave de acesso (required)
     * @param  int $tipo_evento Tipo de evento (required)
     * @param  int $num_seq_evento Número sequencial do evento. Se informado, os demais parâmetros são obrigatórios (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\EventosPostResponseSucesso|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro
     */
    public function eventosGet($chave_acesso, $tipo_evento, $num_seq_evento, string $contentType = self::contentTypes['eventosGet'][0])
    {
        list($response) = $this->eventosGetWithHttpInfo($chave_acesso, $tipo_evento, $num_seq_evento, $contentType);
        return $response;
    }

    /**
     * Operation eventosGetWithHttpInfo
     *
     * Retorna NFS-e e seus eventos relacionados a partir da consulta pela chave de acesso da NFS-e.
     *
     * @param  string $chave_acesso Chave de acesso (required)
     * @param  int $tipo_evento Tipo de evento (required)
     * @param  int $num_seq_evento Número sequencial do evento. Se informado, os demais parâmetros são obrigatórios (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\EventosPostResponseSucesso|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventosGetWithHttpInfo($chave_acesso, $tipo_evento, $num_seq_evento, string $contentType = self::contentTypes['eventosGet'][0])
    {
        $request = $this->eventosGetRequest($chave_acesso, $tipo_evento, $num_seq_evento, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResponseErro',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResponseErro',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResponseErro',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseErro',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseErro',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseErro',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation eventosGetAsync
     *
     * Retorna NFS-e e seus eventos relacionados a partir da consulta pela chave de acesso da NFS-e.
     *
     * @param  string $chave_acesso Chave de acesso (required)
     * @param  int $tipo_evento Tipo de evento (required)
     * @param  int $num_seq_evento Número sequencial do evento. Se informado, os demais parâmetros são obrigatórios (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventosGetAsync($chave_acesso, $tipo_evento, $num_seq_evento, string $contentType = self::contentTypes['eventosGet'][0])
    {
        return $this->eventosGetAsyncWithHttpInfo($chave_acesso, $tipo_evento, $num_seq_evento, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventosGetAsyncWithHttpInfo
     *
     * Retorna NFS-e e seus eventos relacionados a partir da consulta pela chave de acesso da NFS-e.
     *
     * @param  string $chave_acesso Chave de acesso (required)
     * @param  int $tipo_evento Tipo de evento (required)
     * @param  int $num_seq_evento Número sequencial do evento. Se informado, os demais parâmetros são obrigatórios (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventosGetAsyncWithHttpInfo($chave_acesso, $tipo_evento, $num_seq_evento, string $contentType = self::contentTypes['eventosGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\EventosPostResponseSucesso';
        $request = $this->eventosGetRequest($chave_acesso, $tipo_evento, $num_seq_evento, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventosGet'
     *
     * @param  string $chave_acesso Chave de acesso (required)
     * @param  int $tipo_evento Tipo de evento (required)
     * @param  int $num_seq_evento Número sequencial do evento. Se informado, os demais parâmetros são obrigatórios (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function eventosGetRequest($chave_acesso, $tipo_evento, $num_seq_evento, string $contentType = self::contentTypes['eventosGet'][0])
    {

        // verify the required parameter 'chave_acesso' is set
        if ($chave_acesso === null || (is_array($chave_acesso) && count($chave_acesso) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chave_acesso when calling eventosGet'
            );
        }

        // verify the required parameter 'tipo_evento' is set
        if ($tipo_evento === null || (is_array($tipo_evento) && count($tipo_evento) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tipo_evento when calling eventosGet'
            );
        }

        // verify the required parameter 'num_seq_evento' is set
        if ($num_seq_evento === null || (is_array($num_seq_evento) && count($num_seq_evento) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $num_seq_evento when calling eventosGet'
            );
        }


        $resourcePath = '/nfse/{chaveAcesso}/eventos/{tipoEvento}/{numSeqEvento}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($chave_acesso !== null) {
            $resourcePath = str_replace(
                '{' . 'chaveAcesso' . '}',
                ObjectSerializer::toPathValue($chave_acesso),
                $resourcePath
            );
        }
        // path params
        if ($tipo_evento !== null) {
            $resourcePath = str_replace(
                '{' . 'tipoEvento' . '}',
                ObjectSerializer::toPathValue($tipo_evento),
                $resourcePath
            );
        }
        // path params
        if ($num_seq_evento !== null) {
            $resourcePath = str_replace(
                '{' . 'numSeqEvento' . '}',
                ObjectSerializer::toPathValue($num_seq_evento),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation eventosPost
     *
     * Recepciona o Pedido de Registro de Evento e gera Eventos de NFS-e, crédito, débito e apuração.
     *
     * @param  string $chave_acesso chave_acesso (required)
     * @param  \OpenAPI\Client\Model\EventosPostRequest $eventos_post_request Estrutura contendo o pedido de registro de evento compactado             no padrão GZip com representação base64binary (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\EventosPostResponseSucesso|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro
     */
    public function eventosPost($chave_acesso, $eventos_post_request, string $contentType = self::contentTypes['eventosPost'][0])
    {
        list($response) = $this->eventosPostWithHttpInfo($chave_acesso, $eventos_post_request, $contentType);
        return $response;
    }

    /**
     * Operation eventosPostWithHttpInfo
     *
     * Recepciona o Pedido de Registro de Evento e gera Eventos de NFS-e, crédito, débito e apuração.
     *
     * @param  string $chave_acesso (required)
     * @param  \OpenAPI\Client\Model\EventosPostRequest $eventos_post_request Estrutura contendo o pedido de registro de evento compactado             no padrão GZip com representação base64binary (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\EventosPostResponseSucesso|\OpenAPI\Client\Model\ResponseErro|\OpenAPI\Client\Model\ResponseErro, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventosPostWithHttpInfo($chave_acesso, $eventos_post_request, string $contentType = self::contentTypes['eventosPost'][0])
    {
        $request = $this->eventosPostRequest($chave_acesso, $eventos_post_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResponseErro',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResponseErro',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\EventosPostResponseSucesso',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseErro',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseErro',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation eventosPostAsync
     *
     * Recepciona o Pedido de Registro de Evento e gera Eventos de NFS-e, crédito, débito e apuração.
     *
     * @param  string $chave_acesso (required)
     * @param  \OpenAPI\Client\Model\EventosPostRequest $eventos_post_request Estrutura contendo o pedido de registro de evento compactado             no padrão GZip com representação base64binary (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventosPostAsync($chave_acesso, $eventos_post_request, string $contentType = self::contentTypes['eventosPost'][0])
    {
        return $this->eventosPostAsyncWithHttpInfo($chave_acesso, $eventos_post_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventosPostAsyncWithHttpInfo
     *
     * Recepciona o Pedido de Registro de Evento e gera Eventos de NFS-e, crédito, débito e apuração.
     *
     * @param  string $chave_acesso (required)
     * @param  \OpenAPI\Client\Model\EventosPostRequest $eventos_post_request Estrutura contendo o pedido de registro de evento compactado             no padrão GZip com representação base64binary (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventosPostAsyncWithHttpInfo($chave_acesso, $eventos_post_request, string $contentType = self::contentTypes['eventosPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\EventosPostResponseSucesso';
        $request = $this->eventosPostRequest($chave_acesso, $eventos_post_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventosPost'
     *
     * @param  string $chave_acesso (required)
     * @param  \OpenAPI\Client\Model\EventosPostRequest $eventos_post_request Estrutura contendo o pedido de registro de evento compactado             no padrão GZip com representação base64binary (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventosPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function eventosPostRequest($chave_acesso, $eventos_post_request, string $contentType = self::contentTypes['eventosPost'][0])
    {

        // verify the required parameter 'chave_acesso' is set
        if ($chave_acesso === null || (is_array($chave_acesso) && count($chave_acesso) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chave_acesso when calling eventosPost'
            );
        }

        // verify the required parameter 'eventos_post_request' is set
        if ($eventos_post_request === null || (is_array($eventos_post_request) && count($eventos_post_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $eventos_post_request when calling eventosPost'
            );
        }


        $resourcePath = '/nfse/{chaveAcesso}/eventos';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($chave_acesso !== null) {
            $resourcePath = str_replace(
                '{' . 'chaveAcesso' . '}',
                ObjectSerializer::toPathValue($chave_acesso),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($eventos_post_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($eventos_post_request));
            } else {
                $httpBody = $eventos_post_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nfseChaveAcessoEventosGet
     *
     * Retorna os Documentos Fiscais de Serviço do tipo Evento vinculados à chave de acesso informada
     *
     * @param  string $chave_acesso chave_acesso (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nfseChaveAcessoEventosGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\LoteDistribuicaoNSUResponse|\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse
     */
    public function nfseChaveAcessoEventosGet($chave_acesso, string $contentType = self::contentTypes['nfseChaveAcessoEventosGet'][0])
    {
        list($response) = $this->nfseChaveAcessoEventosGetWithHttpInfo($chave_acesso, $contentType);
        return $response;
    }

    /**
     * Operation nfseChaveAcessoEventosGetWithHttpInfo
     *
     * Retorna os Documentos Fiscais de Serviço do tipo Evento vinculados à chave de acesso informada
     *
     * @param  string $chave_acesso (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nfseChaveAcessoEventosGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\LoteDistribuicaoNSUResponse|\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function nfseChaveAcessoEventosGetWithHttpInfo($chave_acesso, string $contentType = self::contentTypes['nfseChaveAcessoEventosGet'][0])
    {
        $request = $this->nfseChaveAcessoEventosGetRequest($chave_acesso, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nfseChaveAcessoEventosGetAsync
     *
     * Retorna os Documentos Fiscais de Serviço do tipo Evento vinculados à chave de acesso informada
     *
     * @param  string $chave_acesso (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nfseChaveAcessoEventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nfseChaveAcessoEventosGetAsync($chave_acesso, string $contentType = self::contentTypes['nfseChaveAcessoEventosGet'][0])
    {
        return $this->nfseChaveAcessoEventosGetAsyncWithHttpInfo($chave_acesso, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nfseChaveAcessoEventosGetAsyncWithHttpInfo
     *
     * Retorna os Documentos Fiscais de Serviço do tipo Evento vinculados à chave de acesso informada
     *
     * @param  string $chave_acesso (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nfseChaveAcessoEventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nfseChaveAcessoEventosGetAsyncWithHttpInfo($chave_acesso, string $contentType = self::contentTypes['nfseChaveAcessoEventosGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\LoteDistribuicaoNSUResponse';
        $request = $this->nfseChaveAcessoEventosGetRequest($chave_acesso, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nfseChaveAcessoEventosGet'
     *
     * @param  string $chave_acesso (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nfseChaveAcessoEventosGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nfseChaveAcessoEventosGetRequest($chave_acesso, string $contentType = self::contentTypes['nfseChaveAcessoEventosGet'][0])
    {

        // verify the required parameter 'chave_acesso' is set
        if ($chave_acesso === null || (is_array($chave_acesso) && count($chave_acesso) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chave_acesso when calling nfseChaveAcessoEventosGet'
            );
        }


        $resourcePath = '/nfse/{ChaveAcesso}/eventos';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($chave_acesso !== null) {
            $resourcePath = str_replace(
                '{' . 'ChaveAcesso' . '}',
                ObjectSerializer::toPathValue($chave_acesso),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
