<?php
/**
 * CertificadoDigital
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CertificadoDigital Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CertificadoDigital implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CertificadoDigital';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'x509_certificate2' => '\OpenAPI\Client\Model\X509Certificate2',
        'x509_chain' => '\OpenAPI\Client\Model\X509Chain',
        'cnpj' => 'string',
        'cpf' => 'string',
        'x509_key_usage_flags' => '\OpenAPI\Client\Model\X509KeyUsageFlags',
        'x509_basic_constraints_extension' => '\OpenAPI\Client\Model\X509BasicConstraintsExtension'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'x509_certificate2' => null,
        'x509_chain' => null,
        'cnpj' => null,
        'cpf' => null,
        'x509_key_usage_flags' => null,
        'x509_basic_constraints_extension' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'x509_certificate2' => false,
        'x509_chain' => false,
        'cnpj' => true,
        'cpf' => true,
        'x509_key_usage_flags' => false,
        'x509_basic_constraints_extension' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'x509_certificate2' => 'x509Certificate2',
        'x509_chain' => 'x509Chain',
        'cnpj' => 'cnpj',
        'cpf' => 'cpf',
        'x509_key_usage_flags' => 'x509KeyUsageFlags',
        'x509_basic_constraints_extension' => 'x509BasicConstraintsExtension'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'x509_certificate2' => 'setX509Certificate2',
        'x509_chain' => 'setX509Chain',
        'cnpj' => 'setCnpj',
        'cpf' => 'setCpf',
        'x509_key_usage_flags' => 'setX509KeyUsageFlags',
        'x509_basic_constraints_extension' => 'setX509BasicConstraintsExtension'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'x509_certificate2' => 'getX509Certificate2',
        'x509_chain' => 'getX509Chain',
        'cnpj' => 'getCnpj',
        'cpf' => 'getCpf',
        'x509_key_usage_flags' => 'getX509KeyUsageFlags',
        'x509_basic_constraints_extension' => 'getX509BasicConstraintsExtension'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('x509_certificate2', $data ?? [], null);
        $this->setIfExists('x509_chain', $data ?? [], null);
        $this->setIfExists('cnpj', $data ?? [], null);
        $this->setIfExists('cpf', $data ?? [], null);
        $this->setIfExists('x509_key_usage_flags', $data ?? [], null);
        $this->setIfExists('x509_basic_constraints_extension', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets x509_certificate2
     *
     * @return \OpenAPI\Client\Model\X509Certificate2|null
     */
    public function getX509Certificate2()
    {
        return $this->container['x509_certificate2'];
    }

    /**
     * Sets x509_certificate2
     *
     * @param \OpenAPI\Client\Model\X509Certificate2|null $x509_certificate2 x509_certificate2
     *
     * @return self
     */
    public function setX509Certificate2($x509_certificate2)
    {
        if (is_null($x509_certificate2)) {
            throw new \InvalidArgumentException('non-nullable x509_certificate2 cannot be null');
        }
        $this->container['x509_certificate2'] = $x509_certificate2;

        return $this;
    }

    /**
     * Gets x509_chain
     *
     * @return \OpenAPI\Client\Model\X509Chain|null
     */
    public function getX509Chain()
    {
        return $this->container['x509_chain'];
    }

    /**
     * Sets x509_chain
     *
     * @param \OpenAPI\Client\Model\X509Chain|null $x509_chain x509_chain
     *
     * @return self
     */
    public function setX509Chain($x509_chain)
    {
        if (is_null($x509_chain)) {
            throw new \InvalidArgumentException('non-nullable x509_chain cannot be null');
        }
        $this->container['x509_chain'] = $x509_chain;

        return $this;
    }

    /**
     * Gets cnpj
     *
     * @return string|null
     */
    public function getCnpj()
    {
        return $this->container['cnpj'];
    }

    /**
     * Sets cnpj
     *
     * @param string|null $cnpj cnpj
     *
     * @return self
     */
    public function setCnpj($cnpj)
    {
        if (is_null($cnpj)) {
            array_push($this->openAPINullablesSetToNull, 'cnpj');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cnpj', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cnpj'] = $cnpj;

        return $this;
    }

    /**
     * Gets cpf
     *
     * @return string|null
     */
    public function getCpf()
    {
        return $this->container['cpf'];
    }

    /**
     * Sets cpf
     *
     * @param string|null $cpf cpf
     *
     * @return self
     */
    public function setCpf($cpf)
    {
        if (is_null($cpf)) {
            array_push($this->openAPINullablesSetToNull, 'cpf');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cpf', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cpf'] = $cpf;

        return $this;
    }

    /**
     * Gets x509_key_usage_flags
     *
     * @return \OpenAPI\Client\Model\X509KeyUsageFlags|null
     */
    public function getX509KeyUsageFlags()
    {
        return $this->container['x509_key_usage_flags'];
    }

    /**
     * Sets x509_key_usage_flags
     *
     * @param \OpenAPI\Client\Model\X509KeyUsageFlags|null $x509_key_usage_flags x509_key_usage_flags
     *
     * @return self
     */
    public function setX509KeyUsageFlags($x509_key_usage_flags)
    {
        if (is_null($x509_key_usage_flags)) {
            throw new \InvalidArgumentException('non-nullable x509_key_usage_flags cannot be null');
        }
        $this->container['x509_key_usage_flags'] = $x509_key_usage_flags;

        return $this;
    }

    /**
     * Gets x509_basic_constraints_extension
     *
     * @return \OpenAPI\Client\Model\X509BasicConstraintsExtension|null
     */
    public function getX509BasicConstraintsExtension()
    {
        return $this->container['x509_basic_constraints_extension'];
    }

    /**
     * Sets x509_basic_constraints_extension
     *
     * @param \OpenAPI\Client\Model\X509BasicConstraintsExtension|null $x509_basic_constraints_extension x509_basic_constraints_extension
     *
     * @return self
     */
    public function setX509BasicConstraintsExtension($x509_basic_constraints_extension)
    {
        if (is_null($x509_basic_constraints_extension)) {
            throw new \InvalidArgumentException('non-nullable x509_basic_constraints_extension cannot be null');
        }
        $this->container['x509_basic_constraints_extension'] = $x509_basic_constraints_extension;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


