<?php
/**
 * CreditoConcedidoDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreditoConcedidoDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreditoConcedidoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreditoConcedidoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'tipo_credito' => '\OpenAPI\Client\Model\TipoCredito',
        'data_expiracao' => '\DateTime',
        'data_competencia' => '\DateTime',
        'motivo_credito' => '\OpenAPI\Client\Model\TipoMotivoCredito',
        'codigo_tributario' => 'int',
        'codigo_municipio' => 'int',
        'nome_municipio' => 'string',
        'uf_municipio' => 'string',
        'inscricao_contribuinte' => 'string',
        'tipo_inscricao_contribuinte' => '\OpenAPI\Client\Model\TipoInscricao',
        'valor_credito' => 'float',
        'saldo_disponivel' => 'float',
        'numero_documento' => 'int',
        'passivel_atualizacao' => '\OpenAPI\Client\Model\TipoSimNao',
        'observacao' => 'string',
        'data_hora_registro' => '\DateTime',
        'data_hora_atualizacao' => '\DateTime',
        'indicador_registro_ativo' => '\OpenAPI\Client\Model\TipoSimNao'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'tipo_credito' => null,
        'data_expiracao' => 'date-time',
        'data_competencia' => 'date-time',
        'motivo_credito' => null,
        'codigo_tributario' => 'int32',
        'codigo_municipio' => 'int32',
        'nome_municipio' => null,
        'uf_municipio' => null,
        'inscricao_contribuinte' => null,
        'tipo_inscricao_contribuinte' => null,
        'valor_credito' => 'double',
        'saldo_disponivel' => 'double',
        'numero_documento' => 'int64',
        'passivel_atualizacao' => null,
        'observacao' => null,
        'data_hora_registro' => 'date-time',
        'data_hora_atualizacao' => 'date-time',
        'indicador_registro_ativo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'tipo_credito' => false,
        'data_expiracao' => false,
        'data_competencia' => false,
        'motivo_credito' => false,
        'codigo_tributario' => false,
        'codigo_municipio' => false,
        'nome_municipio' => true,
        'uf_municipio' => true,
        'inscricao_contribuinte' => true,
        'tipo_inscricao_contribuinte' => false,
        'valor_credito' => false,
        'saldo_disponivel' => false,
        'numero_documento' => false,
        'passivel_atualizacao' => false,
        'observacao' => true,
        'data_hora_registro' => false,
        'data_hora_atualizacao' => false,
        'indicador_registro_ativo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'tipo_credito' => 'tipoCredito',
        'data_expiracao' => 'dataExpiracao',
        'data_competencia' => 'dataCompetencia',
        'motivo_credito' => 'motivoCredito',
        'codigo_tributario' => 'codigoTributario',
        'codigo_municipio' => 'codigoMunicipio',
        'nome_municipio' => 'nomeMunicipio',
        'uf_municipio' => 'ufMunicipio',
        'inscricao_contribuinte' => 'inscricaoContribuinte',
        'tipo_inscricao_contribuinte' => 'tipoInscricaoContribuinte',
        'valor_credito' => 'valorCredito',
        'saldo_disponivel' => 'saldoDisponivel',
        'numero_documento' => 'numeroDocumento',
        'passivel_atualizacao' => 'passivelAtualizacao',
        'observacao' => 'observacao',
        'data_hora_registro' => 'dataHoraRegistro',
        'data_hora_atualizacao' => 'dataHoraAtualizacao',
        'indicador_registro_ativo' => 'indicadorRegistroAtivo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'tipo_credito' => 'setTipoCredito',
        'data_expiracao' => 'setDataExpiracao',
        'data_competencia' => 'setDataCompetencia',
        'motivo_credito' => 'setMotivoCredito',
        'codigo_tributario' => 'setCodigoTributario',
        'codigo_municipio' => 'setCodigoMunicipio',
        'nome_municipio' => 'setNomeMunicipio',
        'uf_municipio' => 'setUfMunicipio',
        'inscricao_contribuinte' => 'setInscricaoContribuinte',
        'tipo_inscricao_contribuinte' => 'setTipoInscricaoContribuinte',
        'valor_credito' => 'setValorCredito',
        'saldo_disponivel' => 'setSaldoDisponivel',
        'numero_documento' => 'setNumeroDocumento',
        'passivel_atualizacao' => 'setPassivelAtualizacao',
        'observacao' => 'setObservacao',
        'data_hora_registro' => 'setDataHoraRegistro',
        'data_hora_atualizacao' => 'setDataHoraAtualizacao',
        'indicador_registro_ativo' => 'setIndicadorRegistroAtivo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'tipo_credito' => 'getTipoCredito',
        'data_expiracao' => 'getDataExpiracao',
        'data_competencia' => 'getDataCompetencia',
        'motivo_credito' => 'getMotivoCredito',
        'codigo_tributario' => 'getCodigoTributario',
        'codigo_municipio' => 'getCodigoMunicipio',
        'nome_municipio' => 'getNomeMunicipio',
        'uf_municipio' => 'getUfMunicipio',
        'inscricao_contribuinte' => 'getInscricaoContribuinte',
        'tipo_inscricao_contribuinte' => 'getTipoInscricaoContribuinte',
        'valor_credito' => 'getValorCredito',
        'saldo_disponivel' => 'getSaldoDisponivel',
        'numero_documento' => 'getNumeroDocumento',
        'passivel_atualizacao' => 'getPassivelAtualizacao',
        'observacao' => 'getObservacao',
        'data_hora_registro' => 'getDataHoraRegistro',
        'data_hora_atualizacao' => 'getDataHoraAtualizacao',
        'indicador_registro_ativo' => 'getIndicadorRegistroAtivo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('tipo_credito', $data ?? [], null);
        $this->setIfExists('data_expiracao', $data ?? [], null);
        $this->setIfExists('data_competencia', $data ?? [], null);
        $this->setIfExists('motivo_credito', $data ?? [], null);
        $this->setIfExists('codigo_tributario', $data ?? [], null);
        $this->setIfExists('codigo_municipio', $data ?? [], null);
        $this->setIfExists('nome_municipio', $data ?? [], null);
        $this->setIfExists('uf_municipio', $data ?? [], null);
        $this->setIfExists('inscricao_contribuinte', $data ?? [], null);
        $this->setIfExists('tipo_inscricao_contribuinte', $data ?? [], null);
        $this->setIfExists('valor_credito', $data ?? [], null);
        $this->setIfExists('saldo_disponivel', $data ?? [], null);
        $this->setIfExists('numero_documento', $data ?? [], null);
        $this->setIfExists('passivel_atualizacao', $data ?? [], null);
        $this->setIfExists('observacao', $data ?? [], null);
        $this->setIfExists('data_hora_registro', $data ?? [], null);
        $this->setIfExists('data_hora_atualizacao', $data ?? [], null);
        $this->setIfExists('indicador_registro_ativo', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tipo_credito
     *
     * @return \OpenAPI\Client\Model\TipoCredito|null
     */
    public function getTipoCredito()
    {
        return $this->container['tipo_credito'];
    }

    /**
     * Sets tipo_credito
     *
     * @param \OpenAPI\Client\Model\TipoCredito|null $tipo_credito tipo_credito
     *
     * @return self
     */
    public function setTipoCredito($tipo_credito)
    {
        if (is_null($tipo_credito)) {
            throw new \InvalidArgumentException('non-nullable tipo_credito cannot be null');
        }
        $this->container['tipo_credito'] = $tipo_credito;

        return $this;
    }

    /**
     * Gets data_expiracao
     *
     * @return \DateTime|null
     */
    public function getDataExpiracao()
    {
        return $this->container['data_expiracao'];
    }

    /**
     * Sets data_expiracao
     *
     * @param \DateTime|null $data_expiracao data_expiracao
     *
     * @return self
     */
    public function setDataExpiracao($data_expiracao)
    {
        if (is_null($data_expiracao)) {
            throw new \InvalidArgumentException('non-nullable data_expiracao cannot be null');
        }
        $this->container['data_expiracao'] = $data_expiracao;

        return $this;
    }

    /**
     * Gets data_competencia
     *
     * @return \DateTime|null
     */
    public function getDataCompetencia()
    {
        return $this->container['data_competencia'];
    }

    /**
     * Sets data_competencia
     *
     * @param \DateTime|null $data_competencia data_competencia
     *
     * @return self
     */
    public function setDataCompetencia($data_competencia)
    {
        if (is_null($data_competencia)) {
            throw new \InvalidArgumentException('non-nullable data_competencia cannot be null');
        }
        $this->container['data_competencia'] = $data_competencia;

        return $this;
    }

    /**
     * Gets motivo_credito
     *
     * @return \OpenAPI\Client\Model\TipoMotivoCredito|null
     */
    public function getMotivoCredito()
    {
        return $this->container['motivo_credito'];
    }

    /**
     * Sets motivo_credito
     *
     * @param \OpenAPI\Client\Model\TipoMotivoCredito|null $motivo_credito motivo_credito
     *
     * @return self
     */
    public function setMotivoCredito($motivo_credito)
    {
        if (is_null($motivo_credito)) {
            throw new \InvalidArgumentException('non-nullable motivo_credito cannot be null');
        }
        $this->container['motivo_credito'] = $motivo_credito;

        return $this;
    }

    /**
     * Gets codigo_tributario
     *
     * @return int|null
     */
    public function getCodigoTributario()
    {
        return $this->container['codigo_tributario'];
    }

    /**
     * Sets codigo_tributario
     *
     * @param int|null $codigo_tributario codigo_tributario
     *
     * @return self
     */
    public function setCodigoTributario($codigo_tributario)
    {
        if (is_null($codigo_tributario)) {
            throw new \InvalidArgumentException('non-nullable codigo_tributario cannot be null');
        }
        $this->container['codigo_tributario'] = $codigo_tributario;

        return $this;
    }

    /**
     * Gets codigo_municipio
     *
     * @return int|null
     */
    public function getCodigoMunicipio()
    {
        return $this->container['codigo_municipio'];
    }

    /**
     * Sets codigo_municipio
     *
     * @param int|null $codigo_municipio codigo_municipio
     *
     * @return self
     */
    public function setCodigoMunicipio($codigo_municipio)
    {
        if (is_null($codigo_municipio)) {
            throw new \InvalidArgumentException('non-nullable codigo_municipio cannot be null');
        }
        $this->container['codigo_municipio'] = $codigo_municipio;

        return $this;
    }

    /**
     * Gets nome_municipio
     *
     * @return string|null
     */
    public function getNomeMunicipio()
    {
        return $this->container['nome_municipio'];
    }

    /**
     * Sets nome_municipio
     *
     * @param string|null $nome_municipio nome_municipio
     *
     * @return self
     */
    public function setNomeMunicipio($nome_municipio)
    {
        if (is_null($nome_municipio)) {
            array_push($this->openAPINullablesSetToNull, 'nome_municipio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nome_municipio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nome_municipio'] = $nome_municipio;

        return $this;
    }

    /**
     * Gets uf_municipio
     *
     * @return string|null
     */
    public function getUfMunicipio()
    {
        return $this->container['uf_municipio'];
    }

    /**
     * Sets uf_municipio
     *
     * @param string|null $uf_municipio uf_municipio
     *
     * @return self
     */
    public function setUfMunicipio($uf_municipio)
    {
        if (is_null($uf_municipio)) {
            array_push($this->openAPINullablesSetToNull, 'uf_municipio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uf_municipio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uf_municipio'] = $uf_municipio;

        return $this;
    }

    /**
     * Gets inscricao_contribuinte
     *
     * @return string|null
     */
    public function getInscricaoContribuinte()
    {
        return $this->container['inscricao_contribuinte'];
    }

    /**
     * Sets inscricao_contribuinte
     *
     * @param string|null $inscricao_contribuinte inscricao_contribuinte
     *
     * @return self
     */
    public function setInscricaoContribuinte($inscricao_contribuinte)
    {
        if (is_null($inscricao_contribuinte)) {
            array_push($this->openAPINullablesSetToNull, 'inscricao_contribuinte');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inscricao_contribuinte', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inscricao_contribuinte'] = $inscricao_contribuinte;

        return $this;
    }

    /**
     * Gets tipo_inscricao_contribuinte
     *
     * @return \OpenAPI\Client\Model\TipoInscricao|null
     */
    public function getTipoInscricaoContribuinte()
    {
        return $this->container['tipo_inscricao_contribuinte'];
    }

    /**
     * Sets tipo_inscricao_contribuinte
     *
     * @param \OpenAPI\Client\Model\TipoInscricao|null $tipo_inscricao_contribuinte tipo_inscricao_contribuinte
     *
     * @return self
     */
    public function setTipoInscricaoContribuinte($tipo_inscricao_contribuinte)
    {
        if (is_null($tipo_inscricao_contribuinte)) {
            throw new \InvalidArgumentException('non-nullable tipo_inscricao_contribuinte cannot be null');
        }
        $this->container['tipo_inscricao_contribuinte'] = $tipo_inscricao_contribuinte;

        return $this;
    }

    /**
     * Gets valor_credito
     *
     * @return float|null
     */
    public function getValorCredito()
    {
        return $this->container['valor_credito'];
    }

    /**
     * Sets valor_credito
     *
     * @param float|null $valor_credito valor_credito
     *
     * @return self
     */
    public function setValorCredito($valor_credito)
    {
        if (is_null($valor_credito)) {
            throw new \InvalidArgumentException('non-nullable valor_credito cannot be null');
        }
        $this->container['valor_credito'] = $valor_credito;

        return $this;
    }

    /**
     * Gets saldo_disponivel
     *
     * @return float|null
     */
    public function getSaldoDisponivel()
    {
        return $this->container['saldo_disponivel'];
    }

    /**
     * Sets saldo_disponivel
     *
     * @param float|null $saldo_disponivel saldo_disponivel
     *
     * @return self
     */
    public function setSaldoDisponivel($saldo_disponivel)
    {
        if (is_null($saldo_disponivel)) {
            throw new \InvalidArgumentException('non-nullable saldo_disponivel cannot be null');
        }
        $this->container['saldo_disponivel'] = $saldo_disponivel;

        return $this;
    }

    /**
     * Gets numero_documento
     *
     * @return int|null
     */
    public function getNumeroDocumento()
    {
        return $this->container['numero_documento'];
    }

    /**
     * Sets numero_documento
     *
     * @param int|null $numero_documento numero_documento
     *
     * @return self
     */
    public function setNumeroDocumento($numero_documento)
    {
        if (is_null($numero_documento)) {
            throw new \InvalidArgumentException('non-nullable numero_documento cannot be null');
        }
        $this->container['numero_documento'] = $numero_documento;

        return $this;
    }

    /**
     * Gets passivel_atualizacao
     *
     * @return \OpenAPI\Client\Model\TipoSimNao|null
     */
    public function getPassivelAtualizacao()
    {
        return $this->container['passivel_atualizacao'];
    }

    /**
     * Sets passivel_atualizacao
     *
     * @param \OpenAPI\Client\Model\TipoSimNao|null $passivel_atualizacao passivel_atualizacao
     *
     * @return self
     */
    public function setPassivelAtualizacao($passivel_atualizacao)
    {
        if (is_null($passivel_atualizacao)) {
            throw new \InvalidArgumentException('non-nullable passivel_atualizacao cannot be null');
        }
        $this->container['passivel_atualizacao'] = $passivel_atualizacao;

        return $this;
    }

    /**
     * Gets observacao
     *
     * @return string|null
     */
    public function getObservacao()
    {
        return $this->container['observacao'];
    }

    /**
     * Sets observacao
     *
     * @param string|null $observacao observacao
     *
     * @return self
     */
    public function setObservacao($observacao)
    {
        if (is_null($observacao)) {
            array_push($this->openAPINullablesSetToNull, 'observacao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('observacao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['observacao'] = $observacao;

        return $this;
    }

    /**
     * Gets data_hora_registro
     *
     * @return \DateTime|null
     */
    public function getDataHoraRegistro()
    {
        return $this->container['data_hora_registro'];
    }

    /**
     * Sets data_hora_registro
     *
     * @param \DateTime|null $data_hora_registro data_hora_registro
     *
     * @return self
     */
    public function setDataHoraRegistro($data_hora_registro)
    {
        if (is_null($data_hora_registro)) {
            throw new \InvalidArgumentException('non-nullable data_hora_registro cannot be null');
        }
        $this->container['data_hora_registro'] = $data_hora_registro;

        return $this;
    }

    /**
     * Gets data_hora_atualizacao
     *
     * @return \DateTime|null
     */
    public function getDataHoraAtualizacao()
    {
        return $this->container['data_hora_atualizacao'];
    }

    /**
     * Sets data_hora_atualizacao
     *
     * @param \DateTime|null $data_hora_atualizacao data_hora_atualizacao
     *
     * @return self
     */
    public function setDataHoraAtualizacao($data_hora_atualizacao)
    {
        if (is_null($data_hora_atualizacao)) {
            throw new \InvalidArgumentException('non-nullable data_hora_atualizacao cannot be null');
        }
        $this->container['data_hora_atualizacao'] = $data_hora_atualizacao;

        return $this;
    }

    /**
     * Gets indicador_registro_ativo
     *
     * @return \OpenAPI\Client\Model\TipoSimNao|null
     */
    public function getIndicadorRegistroAtivo()
    {
        return $this->container['indicador_registro_ativo'];
    }

    /**
     * Sets indicador_registro_ativo
     *
     * @param \OpenAPI\Client\Model\TipoSimNao|null $indicador_registro_ativo indicador_registro_ativo
     *
     * @return self
     */
    public function setIndicadorRegistroAtivo($indicador_registro_ativo)
    {
        if (is_null($indicador_registro_ativo)) {
            throw new \InvalidArgumentException('non-nullable indicador_registro_ativo cannot be null');
        }
        $this->container['indicador_registro_ativo'] = $indicador_registro_ativo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


