<?php
/**
 * DebitoApuradoDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DebitoApuradoDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DebitoApuradoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DebitoApuradoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_debito_apurado' => 'int',
        'id_declaracao' => 'int',
        'tipo_debito' => '\OpenAPI\Client\Model\TipoDebito',
        'codigo_ibge_municipio_incidencia' => 'int',
        'nome_com_uf_municipio_incidencia' => 'string',
        'codigo_uf_incidencia' => 'int',
        'data_competencia' => '\DateTime',
        'codigo_tributacao_nacional' => 'int',
        'codigo_complementar_municipal' => 'int',
        'codigo_secundario_tributo_formatado' => 'string',
        'valor_base_calculo' => 'float',
        'valor_tributo_destacado' => 'float',
        'percentual_aliquota' => 'float',
        'valor_principal_declarado' => 'float',
        'valor_multa_declarado' => 'float',
        'valor_juros_declarado' => 'float',
        'numero_processo' => 'string',
        'numero_auto_infracao' => 'string',
        'numero_sociedade_uniprofissional' => 'int',
        'observacao' => 'string',
        'chave_documento' => 'string',
        'codigo_receita_principal' => 'int',
        'codigo_receita_descricao' => 'string',
        'codigo_receita_multa' => 'int',
        'codigo_receita_juros' => 'int',
        'indicador_registro_ativo' => '\OpenAPI\Client\Model\TipoSimNao',
        'eh_avulso' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id_debito_apurado' => 'int64',
        'id_declaracao' => 'int64',
        'tipo_debito' => null,
        'codigo_ibge_municipio_incidencia' => 'int32',
        'nome_com_uf_municipio_incidencia' => null,
        'codigo_uf_incidencia' => 'int32',
        'data_competencia' => 'date-time',
        'codigo_tributacao_nacional' => 'int32',
        'codigo_complementar_municipal' => 'int32',
        'codigo_secundario_tributo_formatado' => null,
        'valor_base_calculo' => 'double',
        'valor_tributo_destacado' => 'double',
        'percentual_aliquota' => 'double',
        'valor_principal_declarado' => 'double',
        'valor_multa_declarado' => 'double',
        'valor_juros_declarado' => 'double',
        'numero_processo' => null,
        'numero_auto_infracao' => null,
        'numero_sociedade_uniprofissional' => 'int32',
        'observacao' => null,
        'chave_documento' => null,
        'codigo_receita_principal' => 'int32',
        'codigo_receita_descricao' => null,
        'codigo_receita_multa' => 'int32',
        'codigo_receita_juros' => 'int32',
        'indicador_registro_ativo' => null,
        'eh_avulso' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id_debito_apurado' => false,
        'id_declaracao' => false,
        'tipo_debito' => false,
        'codigo_ibge_municipio_incidencia' => false,
        'nome_com_uf_municipio_incidencia' => true,
        'codigo_uf_incidencia' => false,
        'data_competencia' => false,
        'codigo_tributacao_nacional' => false,
        'codigo_complementar_municipal' => true,
        'codigo_secundario_tributo_formatado' => true,
        'valor_base_calculo' => true,
        'valor_tributo_destacado' => true,
        'percentual_aliquota' => true,
        'valor_principal_declarado' => true,
        'valor_multa_declarado' => true,
        'valor_juros_declarado' => true,
        'numero_processo' => true,
        'numero_auto_infracao' => true,
        'numero_sociedade_uniprofissional' => true,
        'observacao' => true,
        'chave_documento' => true,
        'codigo_receita_principal' => false,
        'codigo_receita_descricao' => true,
        'codigo_receita_multa' => false,
        'codigo_receita_juros' => false,
        'indicador_registro_ativo' => false,
        'eh_avulso' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_debito_apurado' => 'idDebitoApurado',
        'id_declaracao' => 'idDeclaracao',
        'tipo_debito' => 'tipoDebito',
        'codigo_ibge_municipio_incidencia' => 'codigoIbgeMunicipioIncidencia',
        'nome_com_uf_municipio_incidencia' => 'nomeComUFMunicipioIncidencia',
        'codigo_uf_incidencia' => 'codigoUFIncidencia',
        'data_competencia' => 'dataCompetencia',
        'codigo_tributacao_nacional' => 'codigoTributacaoNacional',
        'codigo_complementar_municipal' => 'codigoComplementarMunicipal',
        'codigo_secundario_tributo_formatado' => 'codigoSecundarioTributoFormatado',
        'valor_base_calculo' => 'valorBaseCalculo',
        'valor_tributo_destacado' => 'valorTributoDestacado',
        'percentual_aliquota' => 'percentualAliquota',
        'valor_principal_declarado' => 'valorPrincipalDeclarado',
        'valor_multa_declarado' => 'valorMultaDeclarado',
        'valor_juros_declarado' => 'valorJurosDeclarado',
        'numero_processo' => 'numeroProcesso',
        'numero_auto_infracao' => 'numeroAutoInfracao',
        'numero_sociedade_uniprofissional' => 'numeroSociedadeUniprofissional',
        'observacao' => 'observacao',
        'chave_documento' => 'chaveDocumento',
        'codigo_receita_principal' => 'codigoReceitaPrincipal',
        'codigo_receita_descricao' => 'codigoReceitaDescricao',
        'codigo_receita_multa' => 'codigoReceitaMulta',
        'codigo_receita_juros' => 'codigoReceitaJuros',
        'indicador_registro_ativo' => 'indicadorRegistroAtivo',
        'eh_avulso' => 'ehAvulso'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_debito_apurado' => 'setIdDebitoApurado',
        'id_declaracao' => 'setIdDeclaracao',
        'tipo_debito' => 'setTipoDebito',
        'codigo_ibge_municipio_incidencia' => 'setCodigoIbgeMunicipioIncidencia',
        'nome_com_uf_municipio_incidencia' => 'setNomeComUfMunicipioIncidencia',
        'codigo_uf_incidencia' => 'setCodigoUfIncidencia',
        'data_competencia' => 'setDataCompetencia',
        'codigo_tributacao_nacional' => 'setCodigoTributacaoNacional',
        'codigo_complementar_municipal' => 'setCodigoComplementarMunicipal',
        'codigo_secundario_tributo_formatado' => 'setCodigoSecundarioTributoFormatado',
        'valor_base_calculo' => 'setValorBaseCalculo',
        'valor_tributo_destacado' => 'setValorTributoDestacado',
        'percentual_aliquota' => 'setPercentualAliquota',
        'valor_principal_declarado' => 'setValorPrincipalDeclarado',
        'valor_multa_declarado' => 'setValorMultaDeclarado',
        'valor_juros_declarado' => 'setValorJurosDeclarado',
        'numero_processo' => 'setNumeroProcesso',
        'numero_auto_infracao' => 'setNumeroAutoInfracao',
        'numero_sociedade_uniprofissional' => 'setNumeroSociedadeUniprofissional',
        'observacao' => 'setObservacao',
        'chave_documento' => 'setChaveDocumento',
        'codigo_receita_principal' => 'setCodigoReceitaPrincipal',
        'codigo_receita_descricao' => 'setCodigoReceitaDescricao',
        'codigo_receita_multa' => 'setCodigoReceitaMulta',
        'codigo_receita_juros' => 'setCodigoReceitaJuros',
        'indicador_registro_ativo' => 'setIndicadorRegistroAtivo',
        'eh_avulso' => 'setEhAvulso'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_debito_apurado' => 'getIdDebitoApurado',
        'id_declaracao' => 'getIdDeclaracao',
        'tipo_debito' => 'getTipoDebito',
        'codigo_ibge_municipio_incidencia' => 'getCodigoIbgeMunicipioIncidencia',
        'nome_com_uf_municipio_incidencia' => 'getNomeComUfMunicipioIncidencia',
        'codigo_uf_incidencia' => 'getCodigoUfIncidencia',
        'data_competencia' => 'getDataCompetencia',
        'codigo_tributacao_nacional' => 'getCodigoTributacaoNacional',
        'codigo_complementar_municipal' => 'getCodigoComplementarMunicipal',
        'codigo_secundario_tributo_formatado' => 'getCodigoSecundarioTributoFormatado',
        'valor_base_calculo' => 'getValorBaseCalculo',
        'valor_tributo_destacado' => 'getValorTributoDestacado',
        'percentual_aliquota' => 'getPercentualAliquota',
        'valor_principal_declarado' => 'getValorPrincipalDeclarado',
        'valor_multa_declarado' => 'getValorMultaDeclarado',
        'valor_juros_declarado' => 'getValorJurosDeclarado',
        'numero_processo' => 'getNumeroProcesso',
        'numero_auto_infracao' => 'getNumeroAutoInfracao',
        'numero_sociedade_uniprofissional' => 'getNumeroSociedadeUniprofissional',
        'observacao' => 'getObservacao',
        'chave_documento' => 'getChaveDocumento',
        'codigo_receita_principal' => 'getCodigoReceitaPrincipal',
        'codigo_receita_descricao' => 'getCodigoReceitaDescricao',
        'codigo_receita_multa' => 'getCodigoReceitaMulta',
        'codigo_receita_juros' => 'getCodigoReceitaJuros',
        'indicador_registro_ativo' => 'getIndicadorRegistroAtivo',
        'eh_avulso' => 'getEhAvulso'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id_debito_apurado', $data ?? [], null);
        $this->setIfExists('id_declaracao', $data ?? [], null);
        $this->setIfExists('tipo_debito', $data ?? [], null);
        $this->setIfExists('codigo_ibge_municipio_incidencia', $data ?? [], null);
        $this->setIfExists('nome_com_uf_municipio_incidencia', $data ?? [], null);
        $this->setIfExists('codigo_uf_incidencia', $data ?? [], null);
        $this->setIfExists('data_competencia', $data ?? [], null);
        $this->setIfExists('codigo_tributacao_nacional', $data ?? [], null);
        $this->setIfExists('codigo_complementar_municipal', $data ?? [], null);
        $this->setIfExists('codigo_secundario_tributo_formatado', $data ?? [], null);
        $this->setIfExists('valor_base_calculo', $data ?? [], null);
        $this->setIfExists('valor_tributo_destacado', $data ?? [], null);
        $this->setIfExists('percentual_aliquota', $data ?? [], null);
        $this->setIfExists('valor_principal_declarado', $data ?? [], null);
        $this->setIfExists('valor_multa_declarado', $data ?? [], null);
        $this->setIfExists('valor_juros_declarado', $data ?? [], null);
        $this->setIfExists('numero_processo', $data ?? [], null);
        $this->setIfExists('numero_auto_infracao', $data ?? [], null);
        $this->setIfExists('numero_sociedade_uniprofissional', $data ?? [], null);
        $this->setIfExists('observacao', $data ?? [], null);
        $this->setIfExists('chave_documento', $data ?? [], null);
        $this->setIfExists('codigo_receita_principal', $data ?? [], null);
        $this->setIfExists('codigo_receita_descricao', $data ?? [], null);
        $this->setIfExists('codigo_receita_multa', $data ?? [], null);
        $this->setIfExists('codigo_receita_juros', $data ?? [], null);
        $this->setIfExists('indicador_registro_ativo', $data ?? [], null);
        $this->setIfExists('eh_avulso', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_debito_apurado
     *
     * @return int|null
     */
    public function getIdDebitoApurado()
    {
        return $this->container['id_debito_apurado'];
    }

    /**
     * Sets id_debito_apurado
     *
     * @param int|null $id_debito_apurado id_debito_apurado
     *
     * @return self
     */
    public function setIdDebitoApurado($id_debito_apurado)
    {
        if (is_null($id_debito_apurado)) {
            throw new \InvalidArgumentException('non-nullable id_debito_apurado cannot be null');
        }
        $this->container['id_debito_apurado'] = $id_debito_apurado;

        return $this;
    }

    /**
     * Gets id_declaracao
     *
     * @return int|null
     */
    public function getIdDeclaracao()
    {
        return $this->container['id_declaracao'];
    }

    /**
     * Sets id_declaracao
     *
     * @param int|null $id_declaracao id_declaracao
     *
     * @return self
     */
    public function setIdDeclaracao($id_declaracao)
    {
        if (is_null($id_declaracao)) {
            throw new \InvalidArgumentException('non-nullable id_declaracao cannot be null');
        }
        $this->container['id_declaracao'] = $id_declaracao;

        return $this;
    }

    /**
     * Gets tipo_debito
     *
     * @return \OpenAPI\Client\Model\TipoDebito|null
     */
    public function getTipoDebito()
    {
        return $this->container['tipo_debito'];
    }

    /**
     * Sets tipo_debito
     *
     * @param \OpenAPI\Client\Model\TipoDebito|null $tipo_debito tipo_debito
     *
     * @return self
     */
    public function setTipoDebito($tipo_debito)
    {
        if (is_null($tipo_debito)) {
            throw new \InvalidArgumentException('non-nullable tipo_debito cannot be null');
        }
        $this->container['tipo_debito'] = $tipo_debito;

        return $this;
    }

    /**
     * Gets codigo_ibge_municipio_incidencia
     *
     * @return int|null
     */
    public function getCodigoIbgeMunicipioIncidencia()
    {
        return $this->container['codigo_ibge_municipio_incidencia'];
    }

    /**
     * Sets codigo_ibge_municipio_incidencia
     *
     * @param int|null $codigo_ibge_municipio_incidencia codigo_ibge_municipio_incidencia
     *
     * @return self
     */
    public function setCodigoIbgeMunicipioIncidencia($codigo_ibge_municipio_incidencia)
    {
        if (is_null($codigo_ibge_municipio_incidencia)) {
            throw new \InvalidArgumentException('non-nullable codigo_ibge_municipio_incidencia cannot be null');
        }
        $this->container['codigo_ibge_municipio_incidencia'] = $codigo_ibge_municipio_incidencia;

        return $this;
    }

    /**
     * Gets nome_com_uf_municipio_incidencia
     *
     * @return string|null
     */
    public function getNomeComUfMunicipioIncidencia()
    {
        return $this->container['nome_com_uf_municipio_incidencia'];
    }

    /**
     * Sets nome_com_uf_municipio_incidencia
     *
     * @param string|null $nome_com_uf_municipio_incidencia nome_com_uf_municipio_incidencia
     *
     * @return self
     */
    public function setNomeComUfMunicipioIncidencia($nome_com_uf_municipio_incidencia)
    {
        if (is_null($nome_com_uf_municipio_incidencia)) {
            array_push($this->openAPINullablesSetToNull, 'nome_com_uf_municipio_incidencia');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nome_com_uf_municipio_incidencia', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nome_com_uf_municipio_incidencia'] = $nome_com_uf_municipio_incidencia;

        return $this;
    }

    /**
     * Gets codigo_uf_incidencia
     *
     * @return int|null
     */
    public function getCodigoUfIncidencia()
    {
        return $this->container['codigo_uf_incidencia'];
    }

    /**
     * Sets codigo_uf_incidencia
     *
     * @param int|null $codigo_uf_incidencia codigo_uf_incidencia
     *
     * @return self
     */
    public function setCodigoUfIncidencia($codigo_uf_incidencia)
    {
        if (is_null($codigo_uf_incidencia)) {
            throw new \InvalidArgumentException('non-nullable codigo_uf_incidencia cannot be null');
        }
        $this->container['codigo_uf_incidencia'] = $codigo_uf_incidencia;

        return $this;
    }

    /**
     * Gets data_competencia
     *
     * @return \DateTime|null
     */
    public function getDataCompetencia()
    {
        return $this->container['data_competencia'];
    }

    /**
     * Sets data_competencia
     *
     * @param \DateTime|null $data_competencia data_competencia
     *
     * @return self
     */
    public function setDataCompetencia($data_competencia)
    {
        if (is_null($data_competencia)) {
            throw new \InvalidArgumentException('non-nullable data_competencia cannot be null');
        }
        $this->container['data_competencia'] = $data_competencia;

        return $this;
    }

    /**
     * Gets codigo_tributacao_nacional
     *
     * @return int|null
     */
    public function getCodigoTributacaoNacional()
    {
        return $this->container['codigo_tributacao_nacional'];
    }

    /**
     * Sets codigo_tributacao_nacional
     *
     * @param int|null $codigo_tributacao_nacional codigo_tributacao_nacional
     *
     * @return self
     */
    public function setCodigoTributacaoNacional($codigo_tributacao_nacional)
    {
        if (is_null($codigo_tributacao_nacional)) {
            throw new \InvalidArgumentException('non-nullable codigo_tributacao_nacional cannot be null');
        }
        $this->container['codigo_tributacao_nacional'] = $codigo_tributacao_nacional;

        return $this;
    }

    /**
     * Gets codigo_complementar_municipal
     *
     * @return int|null
     */
    public function getCodigoComplementarMunicipal()
    {
        return $this->container['codigo_complementar_municipal'];
    }

    /**
     * Sets codigo_complementar_municipal
     *
     * @param int|null $codigo_complementar_municipal codigo_complementar_municipal
     *
     * @return self
     */
    public function setCodigoComplementarMunicipal($codigo_complementar_municipal)
    {
        if (is_null($codigo_complementar_municipal)) {
            array_push($this->openAPINullablesSetToNull, 'codigo_complementar_municipal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo_complementar_municipal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo_complementar_municipal'] = $codigo_complementar_municipal;

        return $this;
    }

    /**
     * Gets codigo_secundario_tributo_formatado
     *
     * @return string|null
     */
    public function getCodigoSecundarioTributoFormatado()
    {
        return $this->container['codigo_secundario_tributo_formatado'];
    }

    /**
     * Sets codigo_secundario_tributo_formatado
     *
     * @param string|null $codigo_secundario_tributo_formatado codigo_secundario_tributo_formatado
     *
     * @return self
     */
    public function setCodigoSecundarioTributoFormatado($codigo_secundario_tributo_formatado)
    {
        if (is_null($codigo_secundario_tributo_formatado)) {
            array_push($this->openAPINullablesSetToNull, 'codigo_secundario_tributo_formatado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo_secundario_tributo_formatado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo_secundario_tributo_formatado'] = $codigo_secundario_tributo_formatado;

        return $this;
    }

    /**
     * Gets valor_base_calculo
     *
     * @return float|null
     */
    public function getValorBaseCalculo()
    {
        return $this->container['valor_base_calculo'];
    }

    /**
     * Sets valor_base_calculo
     *
     * @param float|null $valor_base_calculo valor_base_calculo
     *
     * @return self
     */
    public function setValorBaseCalculo($valor_base_calculo)
    {
        if (is_null($valor_base_calculo)) {
            array_push($this->openAPINullablesSetToNull, 'valor_base_calculo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valor_base_calculo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valor_base_calculo'] = $valor_base_calculo;

        return $this;
    }

    /**
     * Gets valor_tributo_destacado
     *
     * @return float|null
     */
    public function getValorTributoDestacado()
    {
        return $this->container['valor_tributo_destacado'];
    }

    /**
     * Sets valor_tributo_destacado
     *
     * @param float|null $valor_tributo_destacado valor_tributo_destacado
     *
     * @return self
     */
    public function setValorTributoDestacado($valor_tributo_destacado)
    {
        if (is_null($valor_tributo_destacado)) {
            array_push($this->openAPINullablesSetToNull, 'valor_tributo_destacado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valor_tributo_destacado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valor_tributo_destacado'] = $valor_tributo_destacado;

        return $this;
    }

    /**
     * Gets percentual_aliquota
     *
     * @return float|null
     */
    public function getPercentualAliquota()
    {
        return $this->container['percentual_aliquota'];
    }

    /**
     * Sets percentual_aliquota
     *
     * @param float|null $percentual_aliquota percentual_aliquota
     *
     * @return self
     */
    public function setPercentualAliquota($percentual_aliquota)
    {
        if (is_null($percentual_aliquota)) {
            array_push($this->openAPINullablesSetToNull, 'percentual_aliquota');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('percentual_aliquota', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['percentual_aliquota'] = $percentual_aliquota;

        return $this;
    }

    /**
     * Gets valor_principal_declarado
     *
     * @return float|null
     */
    public function getValorPrincipalDeclarado()
    {
        return $this->container['valor_principal_declarado'];
    }

    /**
     * Sets valor_principal_declarado
     *
     * @param float|null $valor_principal_declarado valor_principal_declarado
     *
     * @return self
     */
    public function setValorPrincipalDeclarado($valor_principal_declarado)
    {
        if (is_null($valor_principal_declarado)) {
            array_push($this->openAPINullablesSetToNull, 'valor_principal_declarado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valor_principal_declarado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valor_principal_declarado'] = $valor_principal_declarado;

        return $this;
    }

    /**
     * Gets valor_multa_declarado
     *
     * @return float|null
     */
    public function getValorMultaDeclarado()
    {
        return $this->container['valor_multa_declarado'];
    }

    /**
     * Sets valor_multa_declarado
     *
     * @param float|null $valor_multa_declarado valor_multa_declarado
     *
     * @return self
     */
    public function setValorMultaDeclarado($valor_multa_declarado)
    {
        if (is_null($valor_multa_declarado)) {
            array_push($this->openAPINullablesSetToNull, 'valor_multa_declarado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valor_multa_declarado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valor_multa_declarado'] = $valor_multa_declarado;

        return $this;
    }

    /**
     * Gets valor_juros_declarado
     *
     * @return float|null
     */
    public function getValorJurosDeclarado()
    {
        return $this->container['valor_juros_declarado'];
    }

    /**
     * Sets valor_juros_declarado
     *
     * @param float|null $valor_juros_declarado valor_juros_declarado
     *
     * @return self
     */
    public function setValorJurosDeclarado($valor_juros_declarado)
    {
        if (is_null($valor_juros_declarado)) {
            array_push($this->openAPINullablesSetToNull, 'valor_juros_declarado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valor_juros_declarado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valor_juros_declarado'] = $valor_juros_declarado;

        return $this;
    }

    /**
     * Gets numero_processo
     *
     * @return string|null
     */
    public function getNumeroProcesso()
    {
        return $this->container['numero_processo'];
    }

    /**
     * Sets numero_processo
     *
     * @param string|null $numero_processo numero_processo
     *
     * @return self
     */
    public function setNumeroProcesso($numero_processo)
    {
        if (is_null($numero_processo)) {
            array_push($this->openAPINullablesSetToNull, 'numero_processo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('numero_processo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['numero_processo'] = $numero_processo;

        return $this;
    }

    /**
     * Gets numero_auto_infracao
     *
     * @return string|null
     */
    public function getNumeroAutoInfracao()
    {
        return $this->container['numero_auto_infracao'];
    }

    /**
     * Sets numero_auto_infracao
     *
     * @param string|null $numero_auto_infracao numero_auto_infracao
     *
     * @return self
     */
    public function setNumeroAutoInfracao($numero_auto_infracao)
    {
        if (is_null($numero_auto_infracao)) {
            array_push($this->openAPINullablesSetToNull, 'numero_auto_infracao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('numero_auto_infracao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['numero_auto_infracao'] = $numero_auto_infracao;

        return $this;
    }

    /**
     * Gets numero_sociedade_uniprofissional
     *
     * @return int|null
     */
    public function getNumeroSociedadeUniprofissional()
    {
        return $this->container['numero_sociedade_uniprofissional'];
    }

    /**
     * Sets numero_sociedade_uniprofissional
     *
     * @param int|null $numero_sociedade_uniprofissional numero_sociedade_uniprofissional
     *
     * @return self
     */
    public function setNumeroSociedadeUniprofissional($numero_sociedade_uniprofissional)
    {
        if (is_null($numero_sociedade_uniprofissional)) {
            array_push($this->openAPINullablesSetToNull, 'numero_sociedade_uniprofissional');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('numero_sociedade_uniprofissional', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['numero_sociedade_uniprofissional'] = $numero_sociedade_uniprofissional;

        return $this;
    }

    /**
     * Gets observacao
     *
     * @return string|null
     */
    public function getObservacao()
    {
        return $this->container['observacao'];
    }

    /**
     * Sets observacao
     *
     * @param string|null $observacao observacao
     *
     * @return self
     */
    public function setObservacao($observacao)
    {
        if (is_null($observacao)) {
            array_push($this->openAPINullablesSetToNull, 'observacao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('observacao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['observacao'] = $observacao;

        return $this;
    }

    /**
     * Gets chave_documento
     *
     * @return string|null
     */
    public function getChaveDocumento()
    {
        return $this->container['chave_documento'];
    }

    /**
     * Sets chave_documento
     *
     * @param string|null $chave_documento chave_documento
     *
     * @return self
     */
    public function setChaveDocumento($chave_documento)
    {
        if (is_null($chave_documento)) {
            array_push($this->openAPINullablesSetToNull, 'chave_documento');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('chave_documento', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['chave_documento'] = $chave_documento;

        return $this;
    }

    /**
     * Gets codigo_receita_principal
     *
     * @return int|null
     */
    public function getCodigoReceitaPrincipal()
    {
        return $this->container['codigo_receita_principal'];
    }

    /**
     * Sets codigo_receita_principal
     *
     * @param int|null $codigo_receita_principal codigo_receita_principal
     *
     * @return self
     */
    public function setCodigoReceitaPrincipal($codigo_receita_principal)
    {
        if (is_null($codigo_receita_principal)) {
            throw new \InvalidArgumentException('non-nullable codigo_receita_principal cannot be null');
        }
        $this->container['codigo_receita_principal'] = $codigo_receita_principal;

        return $this;
    }

    /**
     * Gets codigo_receita_descricao
     *
     * @return string|null
     */
    public function getCodigoReceitaDescricao()
    {
        return $this->container['codigo_receita_descricao'];
    }

    /**
     * Sets codigo_receita_descricao
     *
     * @param string|null $codigo_receita_descricao codigo_receita_descricao
     *
     * @return self
     */
    public function setCodigoReceitaDescricao($codigo_receita_descricao)
    {
        if (is_null($codigo_receita_descricao)) {
            array_push($this->openAPINullablesSetToNull, 'codigo_receita_descricao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo_receita_descricao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo_receita_descricao'] = $codigo_receita_descricao;

        return $this;
    }

    /**
     * Gets codigo_receita_multa
     *
     * @return int|null
     */
    public function getCodigoReceitaMulta()
    {
        return $this->container['codigo_receita_multa'];
    }

    /**
     * Sets codigo_receita_multa
     *
     * @param int|null $codigo_receita_multa codigo_receita_multa
     *
     * @return self
     */
    public function setCodigoReceitaMulta($codigo_receita_multa)
    {
        if (is_null($codigo_receita_multa)) {
            throw new \InvalidArgumentException('non-nullable codigo_receita_multa cannot be null');
        }
        $this->container['codigo_receita_multa'] = $codigo_receita_multa;

        return $this;
    }

    /**
     * Gets codigo_receita_juros
     *
     * @return int|null
     */
    public function getCodigoReceitaJuros()
    {
        return $this->container['codigo_receita_juros'];
    }

    /**
     * Sets codigo_receita_juros
     *
     * @param int|null $codigo_receita_juros codigo_receita_juros
     *
     * @return self
     */
    public function setCodigoReceitaJuros($codigo_receita_juros)
    {
        if (is_null($codigo_receita_juros)) {
            throw new \InvalidArgumentException('non-nullable codigo_receita_juros cannot be null');
        }
        $this->container['codigo_receita_juros'] = $codigo_receita_juros;

        return $this;
    }

    /**
     * Gets indicador_registro_ativo
     *
     * @return \OpenAPI\Client\Model\TipoSimNao|null
     */
    public function getIndicadorRegistroAtivo()
    {
        return $this->container['indicador_registro_ativo'];
    }

    /**
     * Sets indicador_registro_ativo
     *
     * @param \OpenAPI\Client\Model\TipoSimNao|null $indicador_registro_ativo indicador_registro_ativo
     *
     * @return self
     */
    public function setIndicadorRegistroAtivo($indicador_registro_ativo)
    {
        if (is_null($indicador_registro_ativo)) {
            throw new \InvalidArgumentException('non-nullable indicador_registro_ativo cannot be null');
        }
        $this->container['indicador_registro_ativo'] = $indicador_registro_ativo;

        return $this;
    }

    /**
     * Gets eh_avulso
     *
     * @return bool|null
     */
    public function getEhAvulso()
    {
        return $this->container['eh_avulso'];
    }

    /**
     * Sets eh_avulso
     *
     * @param bool|null $eh_avulso eh_avulso
     *
     * @return self
     */
    public function setEhAvulso($eh_avulso)
    {
        if (is_null($eh_avulso)) {
            throw new \InvalidArgumentException('non-nullable eh_avulso cannot be null');
        }
        $this->container['eh_avulso'] = $eh_avulso;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


