<?php
/**
 * DeclaracaoDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DeclaracaoDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeclaracaoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeclaracaoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'certificado_digital' => '\OpenAPI\Client\Model\CertificadoDigital',
        'id_apuracao' => 'int',
        'tipo_inscricao_contribuinte' => '\OpenAPI\Client\Model\TipoInscricao',
        'inscricao_contribuinte' => 'string',
        'nome_contribuinte' => 'string',
        'cod_municipio_contribuinte' => 'int',
        'data_pagamento_desejada' => '\DateTime',
        'tipo_apuracao' => '\OpenAPI\Client\Model\TipoApuracao',
        'data_hora_recimento_apuracao' => '\DateTime',
        'indicador_tributo_recolhido' => '\OpenAPI\Client\Model\TipoSimNao',
        'indicador_registro_ativo' => '\OpenAPI\Client\Model\TipoSimNao',
        'lista_debitos_apuracao' => '\OpenAPI\Client\Model\DebitoApuradoDTO[]',
        'lista_creditos_utilizados_apuracao' => '\OpenAPI\Client\Model\CreditoUtilizadoDTO[]',
        'lista_reducoes_base_calculo_apuracao' => '\OpenAPI\Client\Model\ReducaoBaseCalculoAplicadaDTO[]',
        'dados_recepcao_apuracao' => '\OpenAPI\Client\Model\DadosRecepcaoXmlApuracaoDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'certificado_digital' => null,
        'id_apuracao' => 'int64',
        'tipo_inscricao_contribuinte' => null,
        'inscricao_contribuinte' => null,
        'nome_contribuinte' => null,
        'cod_municipio_contribuinte' => 'int32',
        'data_pagamento_desejada' => 'date-time',
        'tipo_apuracao' => null,
        'data_hora_recimento_apuracao' => 'date-time',
        'indicador_tributo_recolhido' => null,
        'indicador_registro_ativo' => null,
        'lista_debitos_apuracao' => null,
        'lista_creditos_utilizados_apuracao' => null,
        'lista_reducoes_base_calculo_apuracao' => null,
        'dados_recepcao_apuracao' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'certificado_digital' => false,
        'id_apuracao' => false,
        'tipo_inscricao_contribuinte' => false,
        'inscricao_contribuinte' => true,
        'nome_contribuinte' => true,
        'cod_municipio_contribuinte' => true,
        'data_pagamento_desejada' => true,
        'tipo_apuracao' => false,
        'data_hora_recimento_apuracao' => false,
        'indicador_tributo_recolhido' => false,
        'indicador_registro_ativo' => false,
        'lista_debitos_apuracao' => true,
        'lista_creditos_utilizados_apuracao' => true,
        'lista_reducoes_base_calculo_apuracao' => true,
        'dados_recepcao_apuracao' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'certificado_digital' => 'certificadoDigital',
        'id_apuracao' => 'idApuracao',
        'tipo_inscricao_contribuinte' => 'tipoInscricaoContribuinte',
        'inscricao_contribuinte' => 'inscricaoContribuinte',
        'nome_contribuinte' => 'nomeContribuinte',
        'cod_municipio_contribuinte' => 'codMunicipioContribuinte',
        'data_pagamento_desejada' => 'dataPagamentoDesejada',
        'tipo_apuracao' => 'tipoApuracao',
        'data_hora_recimento_apuracao' => 'dataHoraRecimentoApuracao',
        'indicador_tributo_recolhido' => 'indicadorTributoRecolhido',
        'indicador_registro_ativo' => 'indicadorRegistroAtivo',
        'lista_debitos_apuracao' => 'listaDebitosApuracao',
        'lista_creditos_utilizados_apuracao' => 'listaCreditosUtilizadosApuracao',
        'lista_reducoes_base_calculo_apuracao' => 'listaReducoesBaseCalculoApuracao',
        'dados_recepcao_apuracao' => 'dadosRecepcaoApuracao'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'certificado_digital' => 'setCertificadoDigital',
        'id_apuracao' => 'setIdApuracao',
        'tipo_inscricao_contribuinte' => 'setTipoInscricaoContribuinte',
        'inscricao_contribuinte' => 'setInscricaoContribuinte',
        'nome_contribuinte' => 'setNomeContribuinte',
        'cod_municipio_contribuinte' => 'setCodMunicipioContribuinte',
        'data_pagamento_desejada' => 'setDataPagamentoDesejada',
        'tipo_apuracao' => 'setTipoApuracao',
        'data_hora_recimento_apuracao' => 'setDataHoraRecimentoApuracao',
        'indicador_tributo_recolhido' => 'setIndicadorTributoRecolhido',
        'indicador_registro_ativo' => 'setIndicadorRegistroAtivo',
        'lista_debitos_apuracao' => 'setListaDebitosApuracao',
        'lista_creditos_utilizados_apuracao' => 'setListaCreditosUtilizadosApuracao',
        'lista_reducoes_base_calculo_apuracao' => 'setListaReducoesBaseCalculoApuracao',
        'dados_recepcao_apuracao' => 'setDadosRecepcaoApuracao'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'certificado_digital' => 'getCertificadoDigital',
        'id_apuracao' => 'getIdApuracao',
        'tipo_inscricao_contribuinte' => 'getTipoInscricaoContribuinte',
        'inscricao_contribuinte' => 'getInscricaoContribuinte',
        'nome_contribuinte' => 'getNomeContribuinte',
        'cod_municipio_contribuinte' => 'getCodMunicipioContribuinte',
        'data_pagamento_desejada' => 'getDataPagamentoDesejada',
        'tipo_apuracao' => 'getTipoApuracao',
        'data_hora_recimento_apuracao' => 'getDataHoraRecimentoApuracao',
        'indicador_tributo_recolhido' => 'getIndicadorTributoRecolhido',
        'indicador_registro_ativo' => 'getIndicadorRegistroAtivo',
        'lista_debitos_apuracao' => 'getListaDebitosApuracao',
        'lista_creditos_utilizados_apuracao' => 'getListaCreditosUtilizadosApuracao',
        'lista_reducoes_base_calculo_apuracao' => 'getListaReducoesBaseCalculoApuracao',
        'dados_recepcao_apuracao' => 'getDadosRecepcaoApuracao'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('certificado_digital', $data ?? [], null);
        $this->setIfExists('id_apuracao', $data ?? [], null);
        $this->setIfExists('tipo_inscricao_contribuinte', $data ?? [], null);
        $this->setIfExists('inscricao_contribuinte', $data ?? [], null);
        $this->setIfExists('nome_contribuinte', $data ?? [], null);
        $this->setIfExists('cod_municipio_contribuinte', $data ?? [], null);
        $this->setIfExists('data_pagamento_desejada', $data ?? [], null);
        $this->setIfExists('tipo_apuracao', $data ?? [], null);
        $this->setIfExists('data_hora_recimento_apuracao', $data ?? [], null);
        $this->setIfExists('indicador_tributo_recolhido', $data ?? [], null);
        $this->setIfExists('indicador_registro_ativo', $data ?? [], null);
        $this->setIfExists('lista_debitos_apuracao', $data ?? [], null);
        $this->setIfExists('lista_creditos_utilizados_apuracao', $data ?? [], null);
        $this->setIfExists('lista_reducoes_base_calculo_apuracao', $data ?? [], null);
        $this->setIfExists('dados_recepcao_apuracao', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets certificado_digital
     *
     * @return \OpenAPI\Client\Model\CertificadoDigital|null
     */
    public function getCertificadoDigital()
    {
        return $this->container['certificado_digital'];
    }

    /**
     * Sets certificado_digital
     *
     * @param \OpenAPI\Client\Model\CertificadoDigital|null $certificado_digital certificado_digital
     *
     * @return self
     */
    public function setCertificadoDigital($certificado_digital)
    {
        if (is_null($certificado_digital)) {
            throw new \InvalidArgumentException('non-nullable certificado_digital cannot be null');
        }
        $this->container['certificado_digital'] = $certificado_digital;

        return $this;
    }

    /**
     * Gets id_apuracao
     *
     * @return int|null
     */
    public function getIdApuracao()
    {
        return $this->container['id_apuracao'];
    }

    /**
     * Sets id_apuracao
     *
     * @param int|null $id_apuracao id_apuracao
     *
     * @return self
     */
    public function setIdApuracao($id_apuracao)
    {
        if (is_null($id_apuracao)) {
            throw new \InvalidArgumentException('non-nullable id_apuracao cannot be null');
        }
        $this->container['id_apuracao'] = $id_apuracao;

        return $this;
    }

    /**
     * Gets tipo_inscricao_contribuinte
     *
     * @return \OpenAPI\Client\Model\TipoInscricao|null
     */
    public function getTipoInscricaoContribuinte()
    {
        return $this->container['tipo_inscricao_contribuinte'];
    }

    /**
     * Sets tipo_inscricao_contribuinte
     *
     * @param \OpenAPI\Client\Model\TipoInscricao|null $tipo_inscricao_contribuinte tipo_inscricao_contribuinte
     *
     * @return self
     */
    public function setTipoInscricaoContribuinte($tipo_inscricao_contribuinte)
    {
        if (is_null($tipo_inscricao_contribuinte)) {
            throw new \InvalidArgumentException('non-nullable tipo_inscricao_contribuinte cannot be null');
        }
        $this->container['tipo_inscricao_contribuinte'] = $tipo_inscricao_contribuinte;

        return $this;
    }

    /**
     * Gets inscricao_contribuinte
     *
     * @return string|null
     */
    public function getInscricaoContribuinte()
    {
        return $this->container['inscricao_contribuinte'];
    }

    /**
     * Sets inscricao_contribuinte
     *
     * @param string|null $inscricao_contribuinte inscricao_contribuinte
     *
     * @return self
     */
    public function setInscricaoContribuinte($inscricao_contribuinte)
    {
        if (is_null($inscricao_contribuinte)) {
            array_push($this->openAPINullablesSetToNull, 'inscricao_contribuinte');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inscricao_contribuinte', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inscricao_contribuinte'] = $inscricao_contribuinte;

        return $this;
    }

    /**
     * Gets nome_contribuinte
     *
     * @return string|null
     */
    public function getNomeContribuinte()
    {
        return $this->container['nome_contribuinte'];
    }

    /**
     * Sets nome_contribuinte
     *
     * @param string|null $nome_contribuinte nome_contribuinte
     *
     * @return self
     */
    public function setNomeContribuinte($nome_contribuinte)
    {
        if (is_null($nome_contribuinte)) {
            array_push($this->openAPINullablesSetToNull, 'nome_contribuinte');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nome_contribuinte', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nome_contribuinte'] = $nome_contribuinte;

        return $this;
    }

    /**
     * Gets cod_municipio_contribuinte
     *
     * @return int|null
     */
    public function getCodMunicipioContribuinte()
    {
        return $this->container['cod_municipio_contribuinte'];
    }

    /**
     * Sets cod_municipio_contribuinte
     *
     * @param int|null $cod_municipio_contribuinte cod_municipio_contribuinte
     *
     * @return self
     */
    public function setCodMunicipioContribuinte($cod_municipio_contribuinte)
    {
        if (is_null($cod_municipio_contribuinte)) {
            array_push($this->openAPINullablesSetToNull, 'cod_municipio_contribuinte');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cod_municipio_contribuinte', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cod_municipio_contribuinte'] = $cod_municipio_contribuinte;

        return $this;
    }

    /**
     * Gets data_pagamento_desejada
     *
     * @return \DateTime|null
     */
    public function getDataPagamentoDesejada()
    {
        return $this->container['data_pagamento_desejada'];
    }

    /**
     * Sets data_pagamento_desejada
     *
     * @param \DateTime|null $data_pagamento_desejada data_pagamento_desejada
     *
     * @return self
     */
    public function setDataPagamentoDesejada($data_pagamento_desejada)
    {
        if (is_null($data_pagamento_desejada)) {
            array_push($this->openAPINullablesSetToNull, 'data_pagamento_desejada');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_pagamento_desejada', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_pagamento_desejada'] = $data_pagamento_desejada;

        return $this;
    }

    /**
     * Gets tipo_apuracao
     *
     * @return \OpenAPI\Client\Model\TipoApuracao|null
     */
    public function getTipoApuracao()
    {
        return $this->container['tipo_apuracao'];
    }

    /**
     * Sets tipo_apuracao
     *
     * @param \OpenAPI\Client\Model\TipoApuracao|null $tipo_apuracao tipo_apuracao
     *
     * @return self
     */
    public function setTipoApuracao($tipo_apuracao)
    {
        if (is_null($tipo_apuracao)) {
            throw new \InvalidArgumentException('non-nullable tipo_apuracao cannot be null');
        }
        $this->container['tipo_apuracao'] = $tipo_apuracao;

        return $this;
    }

    /**
     * Gets data_hora_recimento_apuracao
     *
     * @return \DateTime|null
     */
    public function getDataHoraRecimentoApuracao()
    {
        return $this->container['data_hora_recimento_apuracao'];
    }

    /**
     * Sets data_hora_recimento_apuracao
     *
     * @param \DateTime|null $data_hora_recimento_apuracao data_hora_recimento_apuracao
     *
     * @return self
     */
    public function setDataHoraRecimentoApuracao($data_hora_recimento_apuracao)
    {
        if (is_null($data_hora_recimento_apuracao)) {
            throw new \InvalidArgumentException('non-nullable data_hora_recimento_apuracao cannot be null');
        }
        $this->container['data_hora_recimento_apuracao'] = $data_hora_recimento_apuracao;

        return $this;
    }

    /**
     * Gets indicador_tributo_recolhido
     *
     * @return \OpenAPI\Client\Model\TipoSimNao|null
     */
    public function getIndicadorTributoRecolhido()
    {
        return $this->container['indicador_tributo_recolhido'];
    }

    /**
     * Sets indicador_tributo_recolhido
     *
     * @param \OpenAPI\Client\Model\TipoSimNao|null $indicador_tributo_recolhido indicador_tributo_recolhido
     *
     * @return self
     */
    public function setIndicadorTributoRecolhido($indicador_tributo_recolhido)
    {
        if (is_null($indicador_tributo_recolhido)) {
            throw new \InvalidArgumentException('non-nullable indicador_tributo_recolhido cannot be null');
        }
        $this->container['indicador_tributo_recolhido'] = $indicador_tributo_recolhido;

        return $this;
    }

    /**
     * Gets indicador_registro_ativo
     *
     * @return \OpenAPI\Client\Model\TipoSimNao|null
     */
    public function getIndicadorRegistroAtivo()
    {
        return $this->container['indicador_registro_ativo'];
    }

    /**
     * Sets indicador_registro_ativo
     *
     * @param \OpenAPI\Client\Model\TipoSimNao|null $indicador_registro_ativo indicador_registro_ativo
     *
     * @return self
     */
    public function setIndicadorRegistroAtivo($indicador_registro_ativo)
    {
        if (is_null($indicador_registro_ativo)) {
            throw new \InvalidArgumentException('non-nullable indicador_registro_ativo cannot be null');
        }
        $this->container['indicador_registro_ativo'] = $indicador_registro_ativo;

        return $this;
    }

    /**
     * Gets lista_debitos_apuracao
     *
     * @return \OpenAPI\Client\Model\DebitoApuradoDTO[]|null
     */
    public function getListaDebitosApuracao()
    {
        return $this->container['lista_debitos_apuracao'];
    }

    /**
     * Sets lista_debitos_apuracao
     *
     * @param \OpenAPI\Client\Model\DebitoApuradoDTO[]|null $lista_debitos_apuracao lista_debitos_apuracao
     *
     * @return self
     */
    public function setListaDebitosApuracao($lista_debitos_apuracao)
    {
        if (is_null($lista_debitos_apuracao)) {
            array_push($this->openAPINullablesSetToNull, 'lista_debitos_apuracao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lista_debitos_apuracao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lista_debitos_apuracao'] = $lista_debitos_apuracao;

        return $this;
    }

    /**
     * Gets lista_creditos_utilizados_apuracao
     *
     * @return \OpenAPI\Client\Model\CreditoUtilizadoDTO[]|null
     */
    public function getListaCreditosUtilizadosApuracao()
    {
        return $this->container['lista_creditos_utilizados_apuracao'];
    }

    /**
     * Sets lista_creditos_utilizados_apuracao
     *
     * @param \OpenAPI\Client\Model\CreditoUtilizadoDTO[]|null $lista_creditos_utilizados_apuracao lista_creditos_utilizados_apuracao
     *
     * @return self
     */
    public function setListaCreditosUtilizadosApuracao($lista_creditos_utilizados_apuracao)
    {
        if (is_null($lista_creditos_utilizados_apuracao)) {
            array_push($this->openAPINullablesSetToNull, 'lista_creditos_utilizados_apuracao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lista_creditos_utilizados_apuracao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lista_creditos_utilizados_apuracao'] = $lista_creditos_utilizados_apuracao;

        return $this;
    }

    /**
     * Gets lista_reducoes_base_calculo_apuracao
     *
     * @return \OpenAPI\Client\Model\ReducaoBaseCalculoAplicadaDTO[]|null
     */
    public function getListaReducoesBaseCalculoApuracao()
    {
        return $this->container['lista_reducoes_base_calculo_apuracao'];
    }

    /**
     * Sets lista_reducoes_base_calculo_apuracao
     *
     * @param \OpenAPI\Client\Model\ReducaoBaseCalculoAplicadaDTO[]|null $lista_reducoes_base_calculo_apuracao lista_reducoes_base_calculo_apuracao
     *
     * @return self
     */
    public function setListaReducoesBaseCalculoApuracao($lista_reducoes_base_calculo_apuracao)
    {
        if (is_null($lista_reducoes_base_calculo_apuracao)) {
            array_push($this->openAPINullablesSetToNull, 'lista_reducoes_base_calculo_apuracao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lista_reducoes_base_calculo_apuracao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lista_reducoes_base_calculo_apuracao'] = $lista_reducoes_base_calculo_apuracao;

        return $this;
    }

    /**
     * Gets dados_recepcao_apuracao
     *
     * @return \OpenAPI\Client\Model\DadosRecepcaoXmlApuracaoDTO|null
     */
    public function getDadosRecepcaoApuracao()
    {
        return $this->container['dados_recepcao_apuracao'];
    }

    /**
     * Sets dados_recepcao_apuracao
     *
     * @param \OpenAPI\Client\Model\DadosRecepcaoXmlApuracaoDTO|null $dados_recepcao_apuracao dados_recepcao_apuracao
     *
     * @return self
     */
    public function setDadosRecepcaoApuracao($dados_recepcao_apuracao)
    {
        if (is_null($dados_recepcao_apuracao)) {
            throw new \InvalidArgumentException('non-nullable dados_recepcao_apuracao cannot be null');
        }
        $this->container['dados_recepcao_apuracao'] = $dados_recepcao_apuracao;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


