<?php
/**
 * DistribuicaoNSU
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DistribuicaoNSU Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DistribuicaoNSU implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DistribuicaoNSU';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nsu' => 'int',
        'chave_acesso' => 'string',
        'tipo_documento' => '\OpenAPI\Client\Model\TipoDocumentoRequisicao',
        'tipo_evento' => '\OpenAPI\Client\Model\TipoEvento',
        'arquivo_xml' => 'string',
        'data_hora_recebimento' => '\DateTime',
        'data_hora_geracao' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nsu' => 'int64',
        'chave_acesso' => null,
        'tipo_documento' => null,
        'tipo_evento' => null,
        'arquivo_xml' => null,
        'data_hora_recebimento' => 'date-time',
        'data_hora_geracao' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nsu' => true,
        'chave_acesso' => true,
        'tipo_documento' => false,
        'tipo_evento' => true,
        'arquivo_xml' => true,
        'data_hora_recebimento' => true,
        'data_hora_geracao' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nsu' => 'NSU',
        'chave_acesso' => 'ChaveAcesso',
        'tipo_documento' => 'TipoDocumento',
        'tipo_evento' => 'TipoEvento',
        'arquivo_xml' => 'ArquivoXml',
        'data_hora_recebimento' => 'DataHoraRecebimento',
        'data_hora_geracao' => 'DataHoraGeracao'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nsu' => 'setNsu',
        'chave_acesso' => 'setChaveAcesso',
        'tipo_documento' => 'setTipoDocumento',
        'tipo_evento' => 'setTipoEvento',
        'arquivo_xml' => 'setArquivoXml',
        'data_hora_recebimento' => 'setDataHoraRecebimento',
        'data_hora_geracao' => 'setDataHoraGeracao'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nsu' => 'getNsu',
        'chave_acesso' => 'getChaveAcesso',
        'tipo_documento' => 'getTipoDocumento',
        'tipo_evento' => 'getTipoEvento',
        'arquivo_xml' => 'getArquivoXml',
        'data_hora_recebimento' => 'getDataHoraRecebimento',
        'data_hora_geracao' => 'getDataHoraGeracao'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nsu', $data ?? [], null);
        $this->setIfExists('chave_acesso', $data ?? [], null);
        $this->setIfExists('tipo_documento', $data ?? [], null);
        $this->setIfExists('tipo_evento', $data ?? [], null);
        $this->setIfExists('arquivo_xml', $data ?? [], null);
        $this->setIfExists('data_hora_recebimento', $data ?? [], null);
        $this->setIfExists('data_hora_geracao', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nsu
     *
     * @return int|null
     */
    public function getNsu()
    {
        return $this->container['nsu'];
    }

    /**
     * Sets nsu
     *
     * @param int|null $nsu nsu
     *
     * @return self
     */
    public function setNsu($nsu)
    {
        if (is_null($nsu)) {
            array_push($this->openAPINullablesSetToNull, 'nsu');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nsu', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nsu'] = $nsu;

        return $this;
    }

    /**
     * Gets chave_acesso
     *
     * @return string|null
     */
    public function getChaveAcesso()
    {
        return $this->container['chave_acesso'];
    }

    /**
     * Sets chave_acesso
     *
     * @param string|null $chave_acesso chave_acesso
     *
     * @return self
     */
    public function setChaveAcesso($chave_acesso)
    {
        if (is_null($chave_acesso)) {
            array_push($this->openAPINullablesSetToNull, 'chave_acesso');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('chave_acesso', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['chave_acesso'] = $chave_acesso;

        return $this;
    }

    /**
     * Gets tipo_documento
     *
     * @return \OpenAPI\Client\Model\TipoDocumentoRequisicao|null
     */
    public function getTipoDocumento()
    {
        return $this->container['tipo_documento'];
    }

    /**
     * Sets tipo_documento
     *
     * @param \OpenAPI\Client\Model\TipoDocumentoRequisicao|null $tipo_documento tipo_documento
     *
     * @return self
     */
    public function setTipoDocumento($tipo_documento)
    {
        if (is_null($tipo_documento)) {
            throw new \InvalidArgumentException('non-nullable tipo_documento cannot be null');
        }
        $this->container['tipo_documento'] = $tipo_documento;

        return $this;
    }

    /**
     * Gets tipo_evento
     *
     * @return \OpenAPI\Client\Model\TipoEvento|null
     */
    public function getTipoEvento()
    {
        return $this->container['tipo_evento'];
    }

    /**
     * Sets tipo_evento
     *
     * @param \OpenAPI\Client\Model\TipoEvento|null $tipo_evento tipo_evento
     *
     * @return self
     */
    public function setTipoEvento($tipo_evento)
    {
        if (is_null($tipo_evento)) {
            array_push($this->openAPINullablesSetToNull, 'tipo_evento');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tipo_evento', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tipo_evento'] = $tipo_evento;

        return $this;
    }

    /**
     * Gets arquivo_xml
     *
     * @return string|null
     */
    public function getArquivoXml()
    {
        return $this->container['arquivo_xml'];
    }

    /**
     * Sets arquivo_xml
     *
     * @param string|null $arquivo_xml arquivo_xml
     *
     * @return self
     */
    public function setArquivoXml($arquivo_xml)
    {
        if (is_null($arquivo_xml)) {
            array_push($this->openAPINullablesSetToNull, 'arquivo_xml');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('arquivo_xml', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['arquivo_xml'] = $arquivo_xml;

        return $this;
    }

    /**
     * Gets data_hora_recebimento
     *
     * @return \DateTime|null
     */
    public function getDataHoraRecebimento()
    {
        return $this->container['data_hora_recebimento'];
    }

    /**
     * Sets data_hora_recebimento
     *
     * @param \DateTime|null $data_hora_recebimento data_hora_recebimento
     *
     * @return self
     */
    public function setDataHoraRecebimento($data_hora_recebimento)
    {
        if (is_null($data_hora_recebimento)) {
            array_push($this->openAPINullablesSetToNull, 'data_hora_recebimento');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_hora_recebimento', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_hora_recebimento'] = $data_hora_recebimento;

        return $this;
    }

    /**
     * Gets data_hora_geracao
     *
     * @return \DateTime|null
     */
    public function getDataHoraGeracao()
    {
        return $this->container['data_hora_geracao'];
    }

    /**
     * Sets data_hora_geracao
     *
     * @param \DateTime|null $data_hora_geracao data_hora_geracao
     *
     * @return self
     */
    public function setDataHoraGeracao($data_hora_geracao)
    {
        if (is_null($data_hora_geracao)) {
            array_push($this->openAPINullablesSetToNull, 'data_hora_geracao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_hora_geracao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_hora_geracao'] = $data_hora_geracao;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


