<?php
/**
 * LoteDistribuicaoNSUResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LoteDistribuicaoNSUResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LoteDistribuicaoNSUResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LoteDistribuicaoNSUResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'status_processamento' => '\OpenAPI\Client\Model\StatusProcessamentoDistribuicao',
        'lote_dfe' => '\OpenAPI\Client\Model\DistribuicaoNSU[]',
        'alertas' => '\OpenAPI\Client\Model\MensagemProcessamento[]',
        'erros' => '\OpenAPI\Client\Model\MensagemProcessamento[]',
        'tipo_ambiente' => '\OpenAPI\Client\Model\TipoAmbiente',
        'versao_aplicativo' => 'string',
        'data_hora_processamento' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'status_processamento' => null,
        'lote_dfe' => null,
        'alertas' => null,
        'erros' => null,
        'tipo_ambiente' => null,
        'versao_aplicativo' => null,
        'data_hora_processamento' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'status_processamento' => false,
        'lote_dfe' => true,
        'alertas' => true,
        'erros' => true,
        'tipo_ambiente' => false,
        'versao_aplicativo' => true,
        'data_hora_processamento' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'status_processamento' => 'StatusProcessamento',
        'lote_dfe' => 'LoteDFe',
        'alertas' => 'Alertas',
        'erros' => 'Erros',
        'tipo_ambiente' => 'TipoAmbiente',
        'versao_aplicativo' => 'VersaoAplicativo',
        'data_hora_processamento' => 'DataHoraProcessamento'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'status_processamento' => 'setStatusProcessamento',
        'lote_dfe' => 'setLoteDfe',
        'alertas' => 'setAlertas',
        'erros' => 'setErros',
        'tipo_ambiente' => 'setTipoAmbiente',
        'versao_aplicativo' => 'setVersaoAplicativo',
        'data_hora_processamento' => 'setDataHoraProcessamento'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'status_processamento' => 'getStatusProcessamento',
        'lote_dfe' => 'getLoteDfe',
        'alertas' => 'getAlertas',
        'erros' => 'getErros',
        'tipo_ambiente' => 'getTipoAmbiente',
        'versao_aplicativo' => 'getVersaoAplicativo',
        'data_hora_processamento' => 'getDataHoraProcessamento'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('status_processamento', $data ?? [], null);
        $this->setIfExists('lote_dfe', $data ?? [], null);
        $this->setIfExists('alertas', $data ?? [], null);
        $this->setIfExists('erros', $data ?? [], null);
        $this->setIfExists('tipo_ambiente', $data ?? [], null);
        $this->setIfExists('versao_aplicativo', $data ?? [], null);
        $this->setIfExists('data_hora_processamento', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status_processamento
     *
     * @return \OpenAPI\Client\Model\StatusProcessamentoDistribuicao|null
     */
    public function getStatusProcessamento()
    {
        return $this->container['status_processamento'];
    }

    /**
     * Sets status_processamento
     *
     * @param \OpenAPI\Client\Model\StatusProcessamentoDistribuicao|null $status_processamento status_processamento
     *
     * @return self
     */
    public function setStatusProcessamento($status_processamento)
    {
        if (is_null($status_processamento)) {
            throw new \InvalidArgumentException('non-nullable status_processamento cannot be null');
        }
        $this->container['status_processamento'] = $status_processamento;

        return $this;
    }

    /**
     * Gets lote_dfe
     *
     * @return \OpenAPI\Client\Model\DistribuicaoNSU[]|null
     */
    public function getLoteDfe()
    {
        return $this->container['lote_dfe'];
    }

    /**
     * Sets lote_dfe
     *
     * @param \OpenAPI\Client\Model\DistribuicaoNSU[]|null $lote_dfe lote_dfe
     *
     * @return self
     */
    public function setLoteDfe($lote_dfe)
    {
        if (is_null($lote_dfe)) {
            array_push($this->openAPINullablesSetToNull, 'lote_dfe');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lote_dfe', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lote_dfe'] = $lote_dfe;

        return $this;
    }

    /**
     * Gets alertas
     *
     * @return \OpenAPI\Client\Model\MensagemProcessamento[]|null
     */
    public function getAlertas()
    {
        return $this->container['alertas'];
    }

    /**
     * Sets alertas
     *
     * @param \OpenAPI\Client\Model\MensagemProcessamento[]|null $alertas alertas
     *
     * @return self
     */
    public function setAlertas($alertas)
    {
        if (is_null($alertas)) {
            array_push($this->openAPINullablesSetToNull, 'alertas');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('alertas', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['alertas'] = $alertas;

        return $this;
    }

    /**
     * Gets erros
     *
     * @return \OpenAPI\Client\Model\MensagemProcessamento[]|null
     */
    public function getErros()
    {
        return $this->container['erros'];
    }

    /**
     * Sets erros
     *
     * @param \OpenAPI\Client\Model\MensagemProcessamento[]|null $erros erros
     *
     * @return self
     */
    public function setErros($erros)
    {
        if (is_null($erros)) {
            array_push($this->openAPINullablesSetToNull, 'erros');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('erros', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['erros'] = $erros;

        return $this;
    }

    /**
     * Gets tipo_ambiente
     *
     * @return \OpenAPI\Client\Model\TipoAmbiente|null
     */
    public function getTipoAmbiente()
    {
        return $this->container['tipo_ambiente'];
    }

    /**
     * Sets tipo_ambiente
     *
     * @param \OpenAPI\Client\Model\TipoAmbiente|null $tipo_ambiente tipo_ambiente
     *
     * @return self
     */
    public function setTipoAmbiente($tipo_ambiente)
    {
        if (is_null($tipo_ambiente)) {
            throw new \InvalidArgumentException('non-nullable tipo_ambiente cannot be null');
        }
        $this->container['tipo_ambiente'] = $tipo_ambiente;

        return $this;
    }

    /**
     * Gets versao_aplicativo
     *
     * @return string|null
     */
    public function getVersaoAplicativo()
    {
        return $this->container['versao_aplicativo'];
    }

    /**
     * Sets versao_aplicativo
     *
     * @param string|null $versao_aplicativo versao_aplicativo
     *
     * @return self
     */
    public function setVersaoAplicativo($versao_aplicativo)
    {
        if (is_null($versao_aplicativo)) {
            array_push($this->openAPINullablesSetToNull, 'versao_aplicativo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('versao_aplicativo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['versao_aplicativo'] = $versao_aplicativo;

        return $this;
    }

    /**
     * Gets data_hora_processamento
     *
     * @return \DateTime|null
     */
    public function getDataHoraProcessamento()
    {
        return $this->container['data_hora_processamento'];
    }

    /**
     * Sets data_hora_processamento
     *
     * @param \DateTime|null $data_hora_processamento data_hora_processamento
     *
     * @return self
     */
    public function setDataHoraProcessamento($data_hora_processamento)
    {
        if (is_null($data_hora_processamento)) {
            throw new \InvalidArgumentException('non-nullable data_hora_processamento cannot be null');
        }
        $this->container['data_hora_processamento'] = $data_hora_processamento;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


