<?php
/**
 * NFSePostResponseErro
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * NFSePostResponseErro Class Doc Comment
 *
 * @category Class
 * @description Estrutura para resposta de erro no processamento do DPS
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NFSePostResponseErro implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NFSePostResponseErro';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tipo_ambiente' => 'int',
        'versao_aplicativo' => 'string',
        'data_hora_processamento' => '\DateTime',
        'id_dps' => 'string',
        'erros' => '\OpenAPI\Client\Model\MensagemProcessamento[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tipo_ambiente' => 'int32',
        'versao_aplicativo' => null,
        'data_hora_processamento' => 'date-time',
        'id_dps' => null,
        'erros' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tipo_ambiente' => false,
        'versao_aplicativo' => false,
        'data_hora_processamento' => false,
        'id_dps' => false,
        'erros' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tipo_ambiente' => 'tipoAmbiente',
        'versao_aplicativo' => 'versaoAplicativo',
        'data_hora_processamento' => 'dataHoraProcessamento',
        'id_dps' => 'idDPS',
        'erros' => 'erros'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tipo_ambiente' => 'setTipoAmbiente',
        'versao_aplicativo' => 'setVersaoAplicativo',
        'data_hora_processamento' => 'setDataHoraProcessamento',
        'id_dps' => 'setIdDps',
        'erros' => 'setErros'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tipo_ambiente' => 'getTipoAmbiente',
        'versao_aplicativo' => 'getVersaoAplicativo',
        'data_hora_processamento' => 'getDataHoraProcessamento',
        'id_dps' => 'getIdDps',
        'erros' => 'getErros'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TIPO_AMBIENTE_NUMBER_1 = 1;
    public const TIPO_AMBIENTE_NUMBER_2 = 2;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoAmbienteAllowableValues()
    {
        return [
            self::TIPO_AMBIENTE_NUMBER_1,
            self::TIPO_AMBIENTE_NUMBER_2,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tipo_ambiente', $data ?? [], null);
        $this->setIfExists('versao_aplicativo', $data ?? [], null);
        $this->setIfExists('data_hora_processamento', $data ?? [], null);
        $this->setIfExists('id_dps', $data ?? [], null);
        $this->setIfExists('erros', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tipo_ambiente'] === null) {
            $invalidProperties[] = "'tipo_ambiente' can't be null";
        }
        $allowedValues = $this->getTipoAmbienteAllowableValues();
        if (!is_null($this->container['tipo_ambiente']) && !in_array($this->container['tipo_ambiente'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tipo_ambiente', must be one of '%s'",
                $this->container['tipo_ambiente'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['versao_aplicativo'] === null) {
            $invalidProperties[] = "'versao_aplicativo' can't be null";
        }
        if ($this->container['data_hora_processamento'] === null) {
            $invalidProperties[] = "'data_hora_processamento' can't be null";
        }
        if ($this->container['erros'] === null) {
            $invalidProperties[] = "'erros' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tipo_ambiente
     *
     * @return int
     */
    public function getTipoAmbiente()
    {
        return $this->container['tipo_ambiente'];
    }

    /**
     * Sets tipo_ambiente
     *
     * @param int $tipo_ambiente Tipo de ambiente (1-Produção | 2-Homologação)
     *
     * @return self
     */
    public function setTipoAmbiente($tipo_ambiente)
    {
        if (is_null($tipo_ambiente)) {
            throw new \InvalidArgumentException('non-nullable tipo_ambiente cannot be null');
        }
        $allowedValues = $this->getTipoAmbienteAllowableValues();
        if (!in_array($tipo_ambiente, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tipo_ambiente', must be one of '%s'",
                    $tipo_ambiente,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_ambiente'] = $tipo_ambiente;

        return $this;
    }

    /**
     * Gets versao_aplicativo
     *
     * @return string
     */
    public function getVersaoAplicativo()
    {
        return $this->container['versao_aplicativo'];
    }

    /**
     * Sets versao_aplicativo
     *
     * @param string $versao_aplicativo Versão do aplicativo que processou a requisição
     *
     * @return self
     */
    public function setVersaoAplicativo($versao_aplicativo)
    {
        if (is_null($versao_aplicativo)) {
            throw new \InvalidArgumentException('non-nullable versao_aplicativo cannot be null');
        }
        $this->container['versao_aplicativo'] = $versao_aplicativo;

        return $this;
    }

    /**
     * Gets data_hora_processamento
     *
     * @return \DateTime
     */
    public function getDataHoraProcessamento()
    {
        return $this->container['data_hora_processamento'];
    }

    /**
     * Sets data_hora_processamento
     *
     * @param \DateTime $data_hora_processamento Data e hora de processamento da requisição
     *
     * @return self
     */
    public function setDataHoraProcessamento($data_hora_processamento)
    {
        if (is_null($data_hora_processamento)) {
            throw new \InvalidArgumentException('non-nullable data_hora_processamento cannot be null');
        }
        $this->container['data_hora_processamento'] = $data_hora_processamento;

        return $this;
    }

    /**
     * Gets id_dps
     *
     * @return string|null
     */
    public function getIdDps()
    {
        return $this->container['id_dps'];
    }

    /**
     * Sets id_dps
     *
     * @param string|null $id_dps Id do DPS (se tiver conseguido capturar do Xml)
     *
     * @return self
     */
    public function setIdDps($id_dps)
    {
        if (is_null($id_dps)) {
            throw new \InvalidArgumentException('non-nullable id_dps cannot be null');
        }
        $this->container['id_dps'] = $id_dps;

        return $this;
    }

    /**
     * Gets erros
     *
     * @return \OpenAPI\Client\Model\MensagemProcessamento[]
     */
    public function getErros()
    {
        return $this->container['erros'];
    }

    /**
     * Sets erros
     *
     * @param \OpenAPI\Client\Model\MensagemProcessamento[] $erros Erro de processamento do DPS
     *
     * @return self
     */
    public function setErros($erros)
    {
        if (is_null($erros)) {
            throw new \InvalidArgumentException('non-nullable erros cannot be null');
        }
        $this->container['erros'] = $erros;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


