<?php
/**
 * TipoEvento
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TipoEvento Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TipoEvento
{
    /**
     * Possible values of this enum
     */
    public const CANCELAMENTO = 'CANCELAMENTO';

    public const SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL = 'SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL';

    public const CANCELAMENTO_POR_SUBSTITUICAO = 'CANCELAMENTO_POR_SUBSTITUICAO';

    public const CANCELAMENTO_DEFERIDO_ANALISE_FISCAL = 'CANCELAMENTO_DEFERIDO_ANALISE_FISCAL';

    public const CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL = 'CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL';

    public const CONFIRMACAO_PRESTADOR = 'CONFIRMACAO_PRESTADOR';

    public const REJEICAO_PRESTADOR = 'REJEICAO_PRESTADOR';

    public const CONFIRMACAO_TOMADOR = 'CONFIRMACAO_TOMADOR';

    public const REJEICAO_TOMADOR = 'REJEICAO_TOMADOR';

    public const CONFIRMACAO_INTERMEDIARIO = 'CONFIRMACAO_INTERMEDIARIO';

    public const REJEICAO_INTERMEDIARIO = 'REJEICAO_INTERMEDIARIO';

    public const CONFIRMACAO_TACITA = 'CONFIRMACAO_TACITA';

    public const ANULACAO_REJEICAO = 'ANULACAO_REJEICAO';

    public const CANCELAMENTO_POR_OFICIO = 'CANCELAMENTO_POR_OFICIO';

    public const BLOQUEIO_POR_OFICIO = 'BLOQUEIO_POR_OFICIO';

    public const DESBLOQUEIO_POR_OFICIO = 'DESBLOQUEIO_POR_OFICIO';

    public const INCLUSAO_NFSE_DAN = 'INCLUSAO_NFSE_DAN';

    public const TRIBUTOS_NFSE_RECOLHIDOS = 'TRIBUTOS_NFSE_RECOLHIDOS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CANCELAMENTO,
            self::SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL,
            self::CANCELAMENTO_POR_SUBSTITUICAO,
            self::CANCELAMENTO_DEFERIDO_ANALISE_FISCAL,
            self::CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL,
            self::CONFIRMACAO_PRESTADOR,
            self::REJEICAO_PRESTADOR,
            self::CONFIRMACAO_TOMADOR,
            self::REJEICAO_TOMADOR,
            self::CONFIRMACAO_INTERMEDIARIO,
            self::REJEICAO_INTERMEDIARIO,
            self::CONFIRMACAO_TACITA,
            self::ANULACAO_REJEICAO,
            self::CANCELAMENTO_POR_OFICIO,
            self::BLOQUEIO_POR_OFICIO,
            self::DESBLOQUEIO_POR_OFICIO,
            self::INCLUSAO_NFSE_DAN,
            self::TRIBUTOS_NFSE_RECOLHIDOS
        ];
    }
}


