<?php
/**
 * X509ChainStatusFlags
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs PARA OS CONTRIBUINTES DO ISSQN NO SISTEMA NACIONAL NFS-e
 *
 * <p><strong>Protocolo de comunicação:</strong> TLS 1.0, TLS 1.1 e TLS 1.2 com autenticação mútua</p>  <p><strong>Formato para troca de mensagens:</strong> JSON</p>  <p><strong>Formato dos documentos da NFS-e:</strong> XML 1.0  <a href =\"https://www.w3.org/TR/REC-xml\"> (https://www.w3.org/TR/REC-xml)</a> </p>   <p><strong>Codificação de caracteres:</strong> UTF-8</p> <p><strong>Certificado digital:</strong> Emitido por Autoridade Certificadora ICP-Brasil, tipo A1 ou A3, CNPJ ou CPF, com \"Autenticação do Cliente\"</p> <p><strong>Padrão de assinatura dos documentos XML:</strong> XMLDSIG <a href=\"https://www.w3.org/TR/xmldsig-core\">  (https://www.w3.org/TR/xmldsig-core/) </a>  </p>    <p><strong>Padrão de compactação dos documentos XML para troca de mensagens:</strong> GZip com representação base64binary</p><br/>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * X509ChainStatusFlags Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class X509ChainStatusFlags
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_0 = 0;

    public const NUMBER_1 = 1;

    public const NUMBER_2 = 2;

    public const NUMBER_4 = 4;

    public const NUMBER_8 = 8;

    public const NUMBER_16 = 16;

    public const NUMBER_32 = 32;

    public const NUMBER_64 = 64;

    public const NUMBER_128 = 128;

    public const NUMBER_256 = 256;

    public const NUMBER_512 = 512;

    public const NUMBER_1024 = 1024;

    public const NUMBER_2048 = 2048;

    public const NUMBER_4096 = 4096;

    public const NUMBER_8192 = 8192;

    public const NUMBER_16384 = 16384;

    public const NUMBER_32768 = 32768;

    public const NUMBER_65536 = 65536;

    public const NUMBER_131072 = 131072;

    public const NUMBER_262144 = 262144;

    public const NUMBER_524288 = 524288;

    public const NUMBER_1048576 = 1048576;

    public const NUMBER_16777216 = 16777216;

    public const NUMBER_33554432 = 33554432;

    public const NUMBER_67108864 = 67108864;

    public const NUMBER_134217728 = 134217728;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_0,
            self::NUMBER_1,
            self::NUMBER_2,
            self::NUMBER_4,
            self::NUMBER_8,
            self::NUMBER_16,
            self::NUMBER_32,
            self::NUMBER_64,
            self::NUMBER_128,
            self::NUMBER_256,
            self::NUMBER_512,
            self::NUMBER_1024,
            self::NUMBER_2048,
            self::NUMBER_4096,
            self::NUMBER_8192,
            self::NUMBER_16384,
            self::NUMBER_32768,
            self::NUMBER_65536,
            self::NUMBER_131072,
            self::NUMBER_262144,
            self::NUMBER_524288,
            self::NUMBER_1048576,
            self::NUMBER_16777216,
            self::NUMBER_33554432,
            self::NUMBER_67108864,
            self::NUMBER_134217728
        ];
    }
}


